### ISSUE TITLE
IntelliSense cannot find variables from typing module

### ISSUE THREAD

**Issue by shermansiu** [microsoft/python-language-server#2041] opened 2020-05-16 04:06 UTC
## Environment data

-   VS Code version: 1.44.2
-   Extension version (available under the Extensions sidebar): 2020.5.78807
-   OS and version: macOS Mojave v10.14.6
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.2, Anaconda
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Relevant/affected Python packages and their versions: typing
-   Relevant/affected Python-related VS Code extensions and their versions: N/A?
-   Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Language Server (python.jediEnabled=false)
-   Value of the `python.languageServer` setting: Microsoft

## Actual behaviour

Trying to navigate to the definition of certain variables defined in the `typing` module fails. This includes but is not limited to `typing.Pattern` and `typing.TYPE_CHECKING`.

This error occurs regardless of whether `from typing import <variables>` or `import typing; typing.<variable>` is used.

Using Ctrl-Click to navigate to the function definition does nothing. Using F12 or the right-click context menu to navigate to the definition causes a pop-up to appear that says, "No definition found for '<variable name>'".

## Steps to reproduce:

1. In a new Python file, type:

```python3
import re
from typing import Pattern, TYPE_CHECKING

if TYPE_CHECKING:
    pass

x: Pattern = re.compile("foo")
```

Try to navigate to the definition of `TYPING` in `if TYPE_CHECKING:` or `Pattern` in `x: Pattern = re.compile("foo")`. VS Code won't be able to find the definition.

However, you can navigate inside the `typing.py` file by Ctrl-Click-ing `typing` in `from typing` and find the two variables defined there.

## Logs
Nothing came up in the logs when trying to navigate to the code definition of the variables mentioned above.

**Comment by jakebailey** [comment] 2020-05-18 17:35
Dupe of #535. These have to be implemented by hand in C#.

**Closed by jakebailey** 2020-05-18 17:35 UTC
