### ISSUE TITLE
"Analyzing in Background" gets stuck ; extension not

### ISSUE THREAD

**Issue by vict0rsch** [microsoft/python-language-server#1708] opened 2019-10-18 18:20 UTC
## Environment data

- VSCode Version: 1.39.2
- Extension version (available under the Extensions sidebar): 2019.10.41019
- OS and version: macOS 10.14.6
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.4 (pyenv)
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
- Jedi or Language Server? language server

## Actual behaviour

Analysis is stuck for some reason, in spite of quitting/reloading window: 

<img width="277" alt="Capture d’écran 2019-10-18 à 14 10 57" src="https://user-images.githubusercontent.com/9283470/67117624-2859f400-f1b1-11e9-8dc9-51d6b5c20606.png">

The value does not change even after 20+ min

## Steps to reproduce:

unknown

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
Starting Microsoft Python language server.
> conda --version
> pyenv root
> python3.7 -c "import sys;print(sys.executable)"
> python3.6 -c "import sys;print(sys.executable)"
> python3 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python -c "import sys;print(sys.executable)"
> ~/Documents/Github/clouds_dist/cloudenv/bin/python -c "import sys;print(sys.executable)"
> conda info --json
> ~/.pyenv/shims/python2 ~/.vscode/extensions/ms-python.python-2019.10.41019/pythonFiles/interpreterInfo.py
> ~/.pyenv/shims/python2 ~/.vscode/extensions/ms-python.python-2019.10.41019/pythonFiles/interpreterInfo.py
> ~/.pyenv/shims/python2.7 ~/.vscode/extensions/ms-python.python-2019.10.41019/pythonFiles/interpreterInfo.py
> ~/.pyenv/shims/python2.7 ~/.vscode/extensions/ms-python.python-2019.10.41019/pythonFiles/interpreterInfo.py
> ~/.pyenv/shims/python3.4 ~/.vscode/extensions/ms-python.python-2019.10.41019/pythonFiles/interpreterInfo.py
> ~/.pyenv/shims/python3.4 ~/.vscode/extensions/ms-python.python-2019.10.41019/pythonFiles/interpreterInfo.py
> ~/.pyenv/shims/python3.5 ~/.vscode/extensions/ms-python.python-2019.10.41019/pythonFiles/interpreterInfo.py
> ~/.pyenv/shims/python3.5 ~/.vscode/extensions/ms-python.python-2019.10.41019/pythonFiles/interpreterInfo.py
> ~/.pyenv/shims/python3.7 ~/.vscode/extensions/ms-python.python-2019.10.41019/pythonFiles/interpreterInfo.py
> ~/.pyenv/shims/python3.7 ~/.vscode/extensions/ms-python.python-2019.10.41019/pythonFiles/interpreterInfo.py
> ~/Documents/Github/clouds_dist/cloudenv/bin/python -m pylint --disable=W503 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text ~/Documents/Github/clouds_dist/src/train.py
cwd: ~/Documents/Github/clouds_dist
> ~/Documents/Github/clouds_dist/cloudenv/bin/python -m pylint --disable=W503 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text ~/Documents/Github/clouds_dist/src/train.py
cwd: ~/Documents/Github/clouds_dist
> ~/Documents/Github/clouds_dist/cloudenv/bin/python -m pycodestyle --ignore=E501,E203,W503,C0330 --max-line-length=88 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~/Documents/Github/clouds_dist/src/train.py
cwd: ~/Documents/Github/clouds_dist
> ~/Documents/Github/clouds_dist/cloudenv/bin/python -m pycodestyle --ignore=E501,E203,W503,C0330 --max-line-length=88 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~/Documents/Github/clouds_dist/src/train.py
cwd: ~/Documents/Github/clouds_dist
##########Linting Output - pycodestyle##########
> conda info --json
> conda --version
##########Linting Output - pylint##########
************* Module src.train
206,0,convention,bad-continuation:Wrong hanging indentation before block (add 4 spaces).
        self, n_epochs, lambda_gan=0.01, lambda_L=1, num_D_accumulations=1, loss="l1"
        ^   |
327,0,convention,bad-continuation:Wrong hanging indentation before block (add 4 spaces).
                    self.total_steps % opts.train.offline_losses_steps == 0
                    ^   |
328,0,convention,bad-continuation:Wrong hanging indentation before block (add 4 spaces).
                    and self.exp is None
                    ^   |
33,0,refactor,too-many-instance-attributes:Too many instance attributes (27/7)
115,22,error,no-member:Module 'torch' has no 'device' member
149,23,error,no-member:Module 'torch' has no 'FloatTensor' member
175,19,error,no-member:Module 'torch' has no 'cat' member
183,23,warning,broad-except:Catching too general exception Exception
264,34,error,no-member:Module 'torch' has no 'ones' member
265,34,error,no-member:Module 'torch' has no 'zeros' member
219,8,warning,unused-variable:Unused variable 'MSE'
250,20,warning,unused-variable:Unused variable 'acc'
264,20,warning,unused-variable:Unused variable 'real_target'
265,20,warning,unused-variable:Unused variable 'fake_target'
205,4,refactor,too-many-statements:Too many statements (64/50)
85,8,warning,attribute-defined-outside-init:Attribute 'total_steps' defined outside __init__
227,8,warning,attribute-defined-outside-init:Attribute 'total_steps' defined outside __init__
115,8,warning,attribute-defined-outside-init:Attribute 'device' defined outside __init__
117,8,warning,attribute-defined-outside-init:Attribute 'trainloader' defined outside __init__
118,8,warning,attribute-defined-outside-init:Attribute 'trainset' defined outside __init__
128,8,warning,attribute-defined-outside-init:Attribute 'gan' defined outside __init__
131,8,warning,attribute-defined-outside-init:Attribute 'g' defined outside __init__
132,8,warning,attribute-defined-outside-init:Attribute 'd' defined outside __init__
134,8,warning,attribute-defined-outside-init:Attribute 'd_optimizer' defined outside __init__
135,8,warning,attribute-defined-outside-init:Attribute 'g_optimizer' defined outside __init__
225,8,warning,attribute-defined-outside-init:Attribute 'times' defined outside __init__
324,16,warning,attribute-defined-outside-init:Attribute 'times' defined outside __init__
242,16,warning,attribute-defined-outside-init:Attribute 'batch' defined outside __init__
254,20,warning,attribute-defined-outside-init:Attribute 'input_tensor' defined outside __init__
256,20,warning,attribute-defined-outside-init:Attribute 'input_tensor' defined outside __init__
425,11,error,undefined-variable:Undefined variable 'get_opts'
13,0,warning,unused-import:Unused torch.nn.functional imported as F
15,0,warning,unused-import:Unused optim imported from torch
16,0,warning,unused-import:Unused transforms imported from torchvision
20,0,warning,unused-import:Unused Zoom imported from src.preprocessing
20,0,warning,unused-import:Unused Rescale imported from src.preprocessing
20,0,warning,unused-import:Unused RemoveNans imported from src.preprocessing
20,0,warning,unused-import:Unused SquashChannels imported from src.preprocessing
20,0,warning,unused-import:Unused CropInnerSquare imported from src.preprocessing
21,0,warning,unused-import:Unused merge_defaults imported from src.utils
21,0,warning,unused-import:Unused load_conf imported from src.utils
21,0,warning,unused-import:Unused sample_param imported from src.utils
3,0,convention,wrong-import-order:standard import "import argparse" should be placed before "from comet_ml import Experiment, OfflineExperiment"
4,0,convention,wrong-import-order:standard import "import os" should be placed before "from comet_ml import Experiment, OfflineExperiment"
5,0,convention,wrong-import-order:standard import "import subprocess" should be placed before "from comet_ml import Experiment, OfflineExperiment"
6,0,convention,wrong-import-order:standard import "import time" should be placed before "from comet_ml import Experiment, OfflineExperiment"
7,0,convention,wrong-import-order:standard import "from datetime import datetime" should be placed before "from comet_ml import Experiment, OfflineExperiment"
8,0,convention,wrong-import-order:standard import "from pathlib import Path" should be placed before "from comet_ml import Experiment, OfflineExperiment"

------------------------------------------------------------------
Your code has been rated at 6.87/10 (previous run: 6.87/10, +0.00)
```

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
None
```

I'm aware of https://github.com/microsoft/python-language-server/issues/869 but conclusions like https://github.com/microsoft/python-language-server/issues/869#issuecomment-525460812 or https://github.com/microsoft/python-language-server/issues/869#issuecomment-524239771 aren'r reasonable in my case

**Comment by jakebailey** [comment] 2019-10-18 19:20
Duplicate of #1601.

Library caching is not recommended. The default for most users is "none", as "system" is still being worked on.

**Closed by jakebailey** 2019-10-18 19:20 UTC
