### ISSUE TITLE
Spurious error report: Inheriting 'Enum', which is not a class.Python(inherit-non-class)

### ISSUE THREAD

**Issue by vistatest** [microsoft/python-language-server#1465] opened 2019-08-21 04:06 UTC
## Environment data

- VS Code version: 1.37.0
- Extension version (available under the Extensions sidebar): 2019.8.30787
- OS and version: MacOS
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.4
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
- Relevant/affected Python packages and their versions: XXX
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): no jedi

## Expected behaviour

Defining enum with no errors.

## Actual behaviour

An error on defining enum:
`Inheriting 'Enum', which is not a class.Python(inherit-non-class)`

## Steps to reproduce:

Define Python 3 enum, e.g.
```
from enum import Enum

class Location(Enum):
  LAST = 'last'
  ALL = 'all'
```
and see error reported in Problems 
and a class name underscored with a yellowish line, hovering above class name brings an error popup

**Comment by CTrando** [comment] 2019-08-22 18:53
Duplicate of #1419. 

Fix is in with #1422. Change is probably not in stable yet. 

You can do 
```
"python.analysis.downloadChannel": "beta"
```
To see the fix or:
```
"python.analysis.disabled": [
    "inherit-non-class"
],
```
To disable the diagnostic, or put `#noqa` on the line to ignore the error for now. 
Sorry for the inconvenience.

**Closed by CTrando** 2019-08-22 18:53 UTC
