### ISSUE TITLE
Request textDocument/completion failed.

### ISSUE THREAD

**Issue by xnone** [Microsoft/python-language-server#758] opened 2019-03-15 02:34 UTC
Keep throwing this error

[Error - 10:32:54 AM] Request textDocument/completion failed.
  Message: unknown document
  Code: -32000 
   at Microsoft.Python.LanguageServer.Implementation.ProjectFiles.GetEntry(Uri documentUri, Boolean throwIfMissing)
   at Microsoft.Python.LanguageServer.Implementation.ProjectFiles.GetEntry(TextDocumentIdentifier document, Nullable`1 expectedVersion, ProjectEntry& entry, PythonAst& tree)
   at Microsoft.Python.LanguageServer.Implementation.Server.Completion(CompletionParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Completion(JToken token, CancellationToken cancellationToken)

**Comment by jakebailey** [comment] 2019-03-15 02:54
Duplicate of #597 (see #423).

**Closed by jakebailey** 2019-03-15 02:54 UTC
