### ISSUE TITLE
Unable to rename symbol

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#1010] opened 2019-04-24 15:15 UTC
@jerryc05 commented on [Tue Apr 23 2019](https://github.com/Microsoft/vscode-python/issues/5441)

## Environment data

- VS Code version: 1.34.0 insider
- Extension version (available under the Extensions sidebar): 2019.3.6558 (4.11881 does not work with intellicode)
- OS and version: Win 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.3
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): system 
- Relevant/affected Python packages and their versions: N/A

## Expected behaviour

successfully rename symbol

## Actual behaviour

`Value cannot be null. Parameter name: path`

## Steps to reproduce:
1. `a = 1`
2. rename `a`

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
Request textDocument/rename failed.
  Message: Value cannot be null.
Parameter name: path
  Code: -32000 
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Microsoft.Python.Core.IO.FileSystem.GetFiles(String path, String pattern, SearchOption option)
   at Microsoft.Python.LanguageServer.Sources.ReferenceSource.ScanClosedFiles(String name, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Sources.ReferenceSource.FindAllReferencesAsync(String name, IPythonModule declaringModule, ILocatedMember rootDefinition, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Sources.ReferenceSource.FindAllReferencesAsync(Uri uri, SourceLocation location, ReferenceSearchOptions options, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Sources.RenameSource.RenameAsync(Uri uri, SourceLocation location, String newName, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Rename(JToken token, CancellationToken cancellationToken)

```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
[Extension Host] {
  "jsonrpc": "2.0",
  "id": 7,
  "method": "textDocument/codeAction",
  "params": {
    "textDocument": {
      "uri": "file:///   HIDDEN"
    },
    "range": {
      "start": {
        "line": 0,
        "character": 11
      },
      "end": {
        "line": 0,
        "character": 11
      }
    },
    "context": {
      "diagnostics": []
    }
  }
}

```

---

@jerryc05 commented on [Tue Apr 23 2019](https://github.com/Microsoft/vscode-python/issues/5441#issuecomment-486093289)

Okay, the problem disappeared when I opened the folder containing this file. However, could you make it still usable without opening the folder?

**Comment by jakebailey** [comment] 2019-04-24 16:25
Duplicate of #1001.

**Closed by jakebailey** 2019-04-24 16:25 UTC
