### ISSUE TITLE
Why is docstring font so huge in scipy?

### ISSUE THREAD

**Issue by pedrogarcia** [microsoft/python-language-server#1685] opened 2019-10-11 20:43 UTC
A huge chunk of the docstring is missing, and what shows up in vscode is mostly the useless part.
![Snipaste_2019-10-11_17-34-15](https://user-images.githubusercontent.com/2473545/66683652-605fb500-ec4e-11e9-9360-96f76a0cfbc8.png)

When I peek the docstring, I get this:
![Snipaste_2019-10-11_17-41-13](https://user-images.githubusercontent.com/2473545/66683742-9a30bb80-ec4e-11e9-9aa6-8615186569a3.png)

**Comment by jakebailey** [comment] 2019-10-14 20:26
Duplicate of #1127.

**Closed by jakebailey** 2019-10-14 20:26 UTC
