### ISSUE TITLE
No usable version of the libssl was foun

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#1007] opened 2019-04-23 19:11 UTC
@futurehome commented on [Thu Apr 18 2019](https://github.com/Microsoft/vscode-python/issues/5373)

Issue Type: <b>Bug</b>

After I upgrade Ubuntu to 19.04, when I launch vscode with a python file, the output panel just shows the log below:

> No usable version of the libssl was found
> [Info  - 8:30:07 AM] Connection to server got closed. Server will restart.
> No usable version of the libssl was found
> [Info  - 8:30:08 AM] Connection to server got closed. Server will restart.
> No usable version of the libssl was found
> [Info  - 8:30:09 AM] Connection to server got closed. Server will restart.
> No usable version of the libssl was found
> [Info  - 8:30:10 AM] Connection to server got closed. Server will restart.
> No usable version of the libssl was found
> [Error - 8:30:11 AM] Connection to server got closed. Server will not be restarted.

Extension version: 2019.3.6558
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 5.0.0-13-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (4 x 2111)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|10.77GB (6.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

</details>

---

@renkun-ken commented on [Sat Apr 20 2019](https://github.com/Microsoft/vscode-python/issues/5373#issuecomment-485106090)

Same here.

---

@DonJayamanne commented on [Sat Apr 20 2019](https://github.com/Microsoft/vscode-python/issues/5373#issuecomment-485136243)

Ubuntu 19 is not yet officially supported.
Prerequisites for using the language server in the python extension can be found here https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x

If you are unable to get around this by installing the dependencies manually, please use the Jedi language server.
To do so, go into your user settings.json file and add the following setting:
`"python.jediEnabled": true`

---

@futurehome commented on [Mon Apr 22 2019](https://github.com/Microsoft/vscode-python/issues/5373#issuecomment-485599766)

@DonJayamanne I'll use jedi instead for now. Thanks.

---

@DonJayamanne commented on [Tue Apr 23 2019](https://github.com/Microsoft/vscode-python/issues/5373#issuecomment-485936457)

Fixes can be found here:
https://github.com/OmniSharp/omnisharp-vscode/issues/3010
https://github.com/OmniSharp/omnisharp-vscode/pull/3011

**Comment by jakebailey** [comment] 2019-04-23 19:13
Duplicate of #1005.

**Closed by jakebailey** 2019-04-23 19:13 UTC
