### ISSUE TITLE
Linux: XDG_CACHE_HOME appears in workspace

### ISSUE THREAD

**Issue by morganhoward** [microsoft/python-language-server#1250] opened 2019-06-22 02:58 UTC
- VSCode Version: 1.35.1
- OS Version: Ubuntu 18.04.2
- ms-python.python extension version: 2019.5.18875

While in VSCode, a folder will appear in the workspace named XDG_CACHE_HOME. In this folder the Microsoft Python Language Server files appear.
```2019-06-21 19:51:18 ➜   tree XDG_CACHE_HOME 
XDG_CACHE_HOME
└── Microsoft
    └── Python Language Server
        └── stubs.v1
            ├── FWOFJr0Ko_9iRSs0ZJrFm8GrsXrDnMEJde9dSr7NewY=
            │   └── python3.pyi
            ├── lxZFQG_YCJATvcHJZPT3KS4tVSXSHe9W0opaD3PnDKQ=
            │   └── apt_pkg.cpython-36m-x86_64-linux-gnu.pyi
            ├── M2KcDmVDYL_Yq1CJMCom4n3OUETWJLIvUfy8ZvHg0Zw=
            │   ├── python3.array.pyi
            │   ├── python3._ast.pyi
            │   ├── python3.atexit.pyi
            │   ├── python3.binascii.pyi
            │   ├── python3._bisect.pyi
            │   ├── python3._blake2.pyi
            │   ├── python3._codecs.pyi
            │   ├── python3._collections.pyi
            │   ├── python3._datetime.pyi
            │   ├── python3.errno.pyi
            │   ├── python3.fcntl.pyi
            │   ├── python3._functools.pyi
            │   ├── python3.gc.pyi
            │   ├── python3.grp.pyi
            │   ├── python3._heapq.pyi
            │   ├── python3._imp.pyi
            │   ├── python3._io.pyi
            │   ├── python3.itertools.pyi
            │   ├── python3._locale.pyi
            │   ├── python3.marshal.pyi
            │   ├── python3.math.pyi
            │   ├── python3._md5.pyi
            │   ├── python3._operator.pyi
            │   ├── python3._pickle.pyi
            │   ├── python3.posix.pyi
            │   ├── python3._posixsubprocess.pyi
            │   ├── python3.pwd.pyi
            │   ├── python3.pyexpat.pyi
            │   ├── python3._random.pyi
            │   ├── python3.select.pyi
            │   ├── python3._sha1.pyi
            │   ├── python3._sha256.pyi
            │   ├── python3._sha3.pyi
            │   ├── python3._sha512.pyi
            │   ├── python3._signal.pyi
            │   ├── python3._socket.pyi
            │   ├── python3._sre.pyi
            │   ├── python3._stat.pyi
            │   ├── python3._string.pyi
            │   ├── python3._struct.pyi
            │   ├── python3.sys.pyi
            │   ├── python3._thread.pyi
            │   ├── python3.time.pyi
            │   ├── python3._tracemalloc.pyi
            │   ├── python3.unicodedata.pyi
            │   ├── python3._warnings.pyi
            │   ├── python3._weakref.pyi
            │   ├── python3.zipimport.pyi
            │   └── python3.zlib.pyi
            └── t3txor45fEPBjGpU2EQBgGE6iSpk6Eqy8MLz4QMxALs=
                ├── _bz2.cpython-36m-x86_64-linux-gnu.pyi
                ├── _ctypes.cpython-36m-x86_64-linux-gnu.pyi
                ├── _decimal.cpython-36m-x86_64-linux-gnu.pyi
                ├── _hashlib.cpython-36m-x86_64-linux-gnu.pyi
                ├── _json.cpython-36m-x86_64-linux-gnu.pyi
                ├── _lzma.cpython-36m-x86_64-linux-gnu.pyi
                ├── mmap.cpython-36m-x86_64-linux-gnu.pyi
                ├── _multiprocessing.cpython-36m-x86_64-linux-gnu.pyi
                ├── _opcode.cpython-36m-x86_64-linux-gnu.pyi
                ├── readline.cpython-36m-x86_64-linux-gnu.pyi
                ├── _ssl.cpython-36m-x86_64-linux-gnu.pyi
                └── termios.cpython-36m-x86_64-linux-gnu.pyi

7 directories, 63 files
```

My XDG_CACHE_HOME is not set, which according to XDG base dir spec (identified here on SO) means that it should use the default, $HOME/.config.
>"If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config 
>should be used".

The occurrence has been consistent in Python projects for me.  If I delete the folder, it reappears the next time I load the workspace and the Python extension is enabled.  If I disable the extension and delete the folder, it does not reappear when I close/open the workspace again.

This was also reported by @drsooch and @autoferrit here: https://github.com/microsoft/vscode/issues/75552

**Comment by DonJayamanne** [comment] 2019-06-24 17:34
@jakebailey 
Please provide a solution/work around for users with existing versions of language server. E.g. uninstall extension, delete ls folder etc..

**Comment by jakebailey** [comment] 2019-06-24 17:48
A workaround would be to switch up to the beta/daily download channels, i.e. set one of:

```json
"python.analysis.downloadChannel": "beta"
```

```json
"python.analysis.downloadChannel": "daily"
```

And reload to update (or force one via vscode-python#3977).

The issue is fixed in 0.3.4 and above, and I plan to push the fix out to everyone (among other fixes) very shortly.

Duplicate of #1197, #1244.

**Closed by jakebailey** 2019-06-24 17:48 UTC

**Comment by DonJayamanne** [comment] 2019-06-24 18:32
Or better, please uninstall the extension, exit VSCode. Reopen VSCode and install the extension again

**Comment by morganhoward** [comment] 2019-06-24 19:31
great!  I added this to my settings,
{code}
"python.analysis.downloadChannel": "daily"
{code}

deleted the XDG_CACHE_HOME, and restarted vscode.  the folder has not shown back up.

thanks for the quick fix!

**Comment by jakebailey** [comment] 2019-06-24 20:02
I've pushed 0.3.20 to stable, so everyone should be getting this fix.
