### ISSUE TITLE
linter trips on nonlocal combined with type hinting

### ISSUE THREAD

**Issue by tdamsma** [microsoft/python-language-server#1644] opened 2019-10-07 11:56 UTC
## Environment data

- VS Code version: 1.38.1
- Extension version (available under the Extensions sidebar): 2019.9.34911
- Python version (& distribution if applicable, e.g. Anaconda): conda, py37
- Jedi or Language Server? I tried both with and without jedi

## As Expected (no issues):

Using nonlocal is supported and throws no errors below:
```python
def outer() -> None:
    x = 1

    def test() -> None:
        nonlocal x
        x = 2
```
However when I add a type I get an error
```python
def outer() -> None:
    x: int = 1

    def test() -> None:
        nonlocal x # no binding for nonlocal 'x' found
        x = 2
```

**Comment by jakebailey** [comment] 2019-10-08 16:36
Duplicate of #121.

**Closed by jakebailey** 2019-10-08 16:36 UTC
