### ISSUE TITLE
Code Navigation not working on Remote Alpine Container when vscode restarted

### ISSUE THREAD

**Issue by moijes12** [microsoft/python-language-server#1987] opened 2020-04-03 06:36 UTC
## Environment data

-   VS Code version: 
Version: 1.44.0-insider (user setup)
Commit: d8e3cca049b1baa317ab9ef0d3f673b08e53d8fa
Date: 2020-04-02T06:42:41.378Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
-   Extension version (available under the Extensions sidebar): ms-python.python
-   OS and version: Windows_NT x64 10.0.18362 (Alpine Python)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): 
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Microsoft Language Server
-   Value of the `python.languageServer` setting: 
Launching server using command /root/.vscode-server-insiders/extensions/ms-python.python-2020.3.71659/languageServer.0.5.45/Microsoft.Python.LanguageServer failed.

## Behavior
The first time build the container and install the Python Extension, I see that the Microsoft Language Server is downloaded and I am prompted to select a python interpreter. Code Navigation works for the entire session. However, if I restart, the machine or VSCode, then Code Navigation does not work even though the extension still shows as installed.

Below are some additional outputs

```
Downloading https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-linux-x64.0.5.45.nupkg...
Downloading https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-linux-x64.0.5.45.nupkg...
Language server download complete
Unpacking archive... done
Language server download complete
Unpacking archive... done
[Error - 6:15:19 AM] Starting client failed
Launching server using command /root/.vscode-server-insiders/extensions/ms-python.python-2020.3.71659/languageServer.0.5.45/Microsoft.Python.LanguageServer failed.
```

**Comment by jakebailey** [comment] 2020-04-07 19:45
Duplicate of #1902.

**Closed by jakebailey** 2020-04-07 19:45 UTC
