### ISSUE TITLE
Badly formatted module description

### ISSUE THREAD

**Issue by memeplex** [microsoft/python-language-server#1127] opened 2019-05-25 03:21 UTC
Probably it's not the language server to blame, but I get this one with the latest beta:

![image](https://user-images.githubusercontent.com/2845433/58363945-d2438780-7e82-11e9-8b65-480a7aaa9fc0.png)

Btw, despite the deficiency noted here (this is not place for sweet words) it looks amazing the level of formatting you are doing there!

**Comment by jakebailey** [comment] 2019-05-25 05:36
It is (mostly); the issue is that numpy is annotated with ReST sections which have different rules and look compared to markdown. That header (the entire sentence) gets converted to the title-level markdown header, which VS Code displays as very, very large. It'be good to tone these down, though that'll take some effort (as right now we can do some mostly effective conversion by passing something like a line above a `-------` unchanged).

**Comment by MikhailArkhipov** [comment] 2019-06-01 17:30
Although text is large lines technically should not be overlapping. Might be line spacing CSS issue in VSC markdown renderer itself. However, we may choose not to use header scales beyond certain threshold.

**Comment by jakebailey** [comment] 2020-04-22 21:55
Closing in favor of #613.

**Closed by jakebailey** 2020-04-22 21:55 UTC
Labels: feature: tooltips
