### ISSUE TITLE
go to definition not work for system libs

### ISSUE THREAD

**Issue by clor09** [microsoft/python-language-server#1747] opened 2019-11-03 05:17 UTC
## Environment data

- VS Code version: m using the oss version, 1.39.2
- Extension version (available under the Extensions sidebar): 2019.10.44104 (not sure if this is the version num? strange schema)
- OS and version: archlinux
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.4
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: all
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Language Server

## Expected behaviour

e.g:  In builtin `socketserver`, when ctrl+click on the `UDPServer` in sentence `class ThreadingUDPServer(ThreadingMixIn, UDPServer): pass`, vsc should bring me to UDPServer definition, but it not

## Actual behaviour

As descripted in Expected behaviour, but Jedi worked in that situation

## Steps to reproduce:
1. create a py file anywhere. import socketserver(or any other py builtin std library) at the header of this file
2. write some code, e.g
`class TestServer(socketserver.ThreadingTCPServer): pass`
3. follow this path, go to ThreadingTCPServer definition -> go to TCPServer definition

## Logs
seems got no error 
```
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - control'
User belongs to experiment group 'LS - control'
> conda --version
> pyenv root
> python3.7 -c "import sys;print(sys.executable)"
> python3.6 -c "import sys;print(sys.executable)"
> python3 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python -c "import sys;print(sys.executable)"
> python -c "import sys;print(sys.executable)"
> conda info --json
Starting Microsoft Python language server.
> conda info --json
> conda --version
```

no output in `Developer Tools` panel

**Comment by jakebailey** [comment] 2019-11-04 22:05
Duplicate of #840. Navigation/hover/completion/etc not working outside the workspace is the current expected behavior.

**Closed by jakebailey** 2019-11-04 22:05 UTC
