### ISSUE TITLE
python code outline broken for multi-root workspaces

### ISSUE THREAD

**Issue by GordonRoule** [microsoft/python-language-server#1275] opened 2019-07-03 15:29 UTC
## Environment data

- Extension version (available under the Extensions sidebar): 2019.6.22090
- VS Code version:
Version: 1.35.1
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:27:31.086Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-51-generic (Ubuntu 18.04 with official updates)

- Python version 2.7.15+
- Type of virtual environment used: N/A
- Relevant/affected Python packages and their versions: NA
- Jedi or Language Server? "python.jediEnabled" is disabled at all levels (see attached)

## Expected behaviour

when editing files in different roots, expect to see code outline in Explorer/Outline sidebar for current file

## Actual behaviour

outline works only for files in 1 root folder

## Steps to reproduce:

I've created a sample workspace (see attached)

1. open workspace and edit root1/file1.py and root2/file2.py
2. code outline is only shown for one of these files

note: if you edit the test.code-workspace file and invert the entries in "folders", then the outline works for both files, however, after reopening the workspace outline works for only the first root in the "folders" list

[vscode-py-outline-issue.zip](https://github.com/microsoft/vscode-python/files/3355672/vscode-py-outline-issue.zip)

**Comment by jakebailey** [comment] 2019-10-11 17:38
I'm going to close this as a duplicate of #1536, even though this one is older (as the other one has more activity).

**Closed by jakebailey** 2019-10-11 17:38 UTC
