### ISSUE TITLE
Go to symbol in workspace fails

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#419] opened 2018-11-19 23:31 UTC
* Language Server version `0.1.63`
* Open PTVSD repo
* Open the file `src/ptvsd/_remote.py`
* From the command palette select `Go to symbol in workspace`
* Kaboom:

```
Starting Microsoft Python language server.
Microsoft Python Language Server version 0.1.63.0
Initializing for /Users/donjayamanne/.local/share/virtualenvs/Algorithm-Y3rXutxy/bin/python
[Error - 3:26:01 PM] Request workspace/symbol failed.
  Message: Object reference not set to an instance of an object.
  Code: -32000 
   at Microsoft.Python.LanguageServer.Implementation.Server.<>c__DisplayClass133_0.<GetModuleVariables>b__4(ILocationInfo l)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Python.LanguageServer.Implementation.Server.<>c__DisplayClass133_0.<GetModuleVariables>b__2(IMemberResult m)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.EnumerablePartition`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Python.LanguageServer.Implementation.Server.GetModuleVariablesAsync(ProjectEntry entry, GetMemberOptions opts, String prefix, Int32 timeout, CancellationToken token)
   at Microsoft.Python.LanguageServer.Implementation.Server.WorkspaceSymbols(WorkspaceSymbolParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.WorkspaceSymbols(JToken token, CancellationToken cancellationToken)
```

**Comment by jakebailey** [comment] 2018-11-19 23:32
Duplicate of #419.

**Closed by jakebailey** 2018-11-19 23:32 UTC

**Comment by jakebailey** [comment] 2018-11-19 23:34
Err, I mean #378.
