### ISSUE TITLE
Autocomplete not working!

### ISSUE THREAD

**Issue by melkayam92** [microsoft/python-language-server#1712] opened 2019-10-22 11:20 UTC
## Environment data

- Language Server version: Microsoft Python Language Server version 0.4.72.0  
- OS and version: macOS Mojave  10.14.5
- Python version (& distribution if applicable, e.g. Anaconda): pyenv 3.7.1 

## Expected behaviour

Autocomplete to work fine, it does recognize variables and imports and so on.

## Actual behaviour

Autocomplete + IntelliSense isn't workin at all, not recognize variables and nothing. 

![Screen Shot 2019-10-22 at 13 55 56](https://user-images.githubusercontent.com/8774744/67280674-59e6fe00-f4d6-11e9-987c-f9c0172ab0de.png)

## Logs

```
Analysis of core.image_cropper (User) queued. Dependencies: core, core.settings
Analysis version 645 of 476 entries has started.
Analysis of _io(CompiledBuiltin) canceled (no AST yet).
Analysis of _weakref(CompiledBuiltin) canceled (no AST yet).
Analysis of pwd(CompiledBuiltin) canceled (no AST yet).
Analysis of _warnings(CompiledBuiltin) canceled (no AST yet).
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis of time(CompiledBuiltin) canceled (no AST yet).
Analysis of _string(CompiledBuiltin) canceled (no AST yet).
Analysis of posix(CompiledBuiltin) canceled (no AST yet).
Analysis of _abc(CompiledBuiltin) canceled (no AST yet).
Analysis of _stat(CompiledBuiltin) canceled (no AST yet).
Analysis of errno(CompiledBuiltin) canceled (no AST yet).
Analysis of _tracemalloc(CompiledBuiltin) canceled (no AST yet).
Analysis of _signal(CompiledBuiltin) canceled (no AST yet).
Analysis of atexit(CompiledBuiltin) canceled (no AST yet).
Analysis of gc(CompiledBuiltin) canceled (no AST yet).
Analysis of _operator(CompiledBuiltin) canceled (no AST yet).
Analysis of _locale(CompiledBuiltin) canceled (no AST yet).
Analysis of abc (Stub) on depth 3 completed in 0.39 ms.
Analysis of _codecs(CompiledBuiltin) canceled (no AST yet).
Analysis of _sre(CompiledBuiltin) canceled (no AST yet).
Analysis of posix (Stub) on depth 3 completed in 0.44 ms.
Analysis of _imp(CompiledBuiltin) canceled (no AST yet).
Analysis of zipimport(CompiledBuiltin) canceled (no AST yet).
Analysis of itertools(CompiledBuiltin) canceled (no AST yet).
Analysis of _collections(CompiledBuiltin) canceled (no AST yet).
Analysis of _thread(CompiledBuiltin) canceled (no AST yet).
Analysis of _functools(CompiledBuiltin) canceled (no AST yet).
Analysis of _ast(CompiledBuiltin) canceled (no AST yet).
Analysis of marshal(CompiledBuiltin) canceled (no AST yet).
Analysis of mmap (Stub) on depth 4 completed in 0.8 ms.
Analysis version 645 has been completed in 1.24 ms with 30 entries analyzed and 446 entries skipped.
Analysis of core.image_cropper (User) queued. Dependencies: core, core.settings
Analysis version 646 of 476 entries has started.
Analysis of _io(CompiledBuiltin) canceled (no AST yet).
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis of posix(CompiledBuiltin) canceled (no AST yet).
Analysis of pwd(CompiledBuiltin) canceled (no AST yet).
Analysis of _stat(CompiledBuiltin) canceled (no AST yet).
Analysis of time(CompiledBuiltin) canceled (no AST yet).
Analysis of _abc(CompiledBuiltin) canceled (no AST yet).
Analysis of errno(CompiledBuiltin) canceled (no AST yet).
Analysis of itertools(CompiledBuiltin) canceled (no AST yet).
Analysis of _weakref(CompiledBuiltin) canceled (no AST yet).
Analysis of _collections(CompiledBuiltin) canceled (no AST yet).
Analysis of _warnings(CompiledBuiltin) canceled (no AST yet).
Analysis of _string(CompiledBuiltin) canceled (no AST yet).
Analysis of _tracemalloc(CompiledBuiltin) canceled (no AST yet).
Analysis of atexit(CompiledBuiltin) canceled (no AST yet).
Analysis of _thread(CompiledBuiltin) canceled (no AST yet).
Analysis of _operator(CompiledBuiltin) canceled (no AST yet).
Analysis of _codecs(CompiledBuiltin) canceled (no AST yet).
Analysis of _functools(CompiledBuiltin) canceled (no AST yet).
Analysis of _sre(CompiledBuiltin) canceled (no AST yet).
Analysis of _signal(CompiledBuiltin) canceled (no AST yet).
Analysis of marshal(CompiledBuiltin) canceled (no AST yet).
Analysis of zipimport(CompiledBuiltin) canceled (no AST yet).
Analysis of gc(CompiledBuiltin) canceled (no AST yet).
Analysis of _locale(CompiledBuiltin) canceled (no AST yet).
Analysis of _ast(CompiledBuiltin) canceled (no AST yet).
Analysis of _imp(CompiledBuiltin) canceled (no AST yet).
Analysis of posix (Stub) on depth 3 completed in 0.46 ms.
Analysis of abc (Stub) on depth 3 completed in 0.49 ms.
Analysis of mmap (Stub) on depth 4 completed in 0.9 ms.
Analysis version 646 has been completed in 1.27 ms with 30 entries analyzed and 446 entries skipped.
Completions in file:///Users/moshe/dev/private/eliran/loto-python-test/core/image_cropper.py at (121, 1)
IntelliCode identified no likely completion items.
Completions in file:///Users/moshe/dev/private/eliran/loto-python-test/core/image_cropper.py at (121, 2)
Analysis of core.image_cropper (User) queued. Dependencies: core, core.settings
Analysis version 647 of 476 entries has started.
Analysis of _io(CompiledBuiltin) canceled (no AST yet).
Analysis of _weakref(CompiledBuiltin) canceled (no AST yet).
Analysis of pwd(CompiledBuiltin) canceled (no AST yet).
Analysis of _warnings(CompiledBuiltin) canceled (no AST yet).
Analysis of time(CompiledBuiltin) canceled (no AST yet).
Analysis of errno(CompiledBuiltin) canceled (no AST yet).
Analysis of _string(CompiledBuiltin) canceled (no AST yet).
Analysis of _tracemalloc(CompiledBuiltin) canceled (no AST yet).
Analysis of itertools(CompiledBuiltin) canceled (no AST yet).
Analysis of _collections(CompiledBuiltin) canceled (no AST yet).
Analysis of sys(CompiledBuiltin) canceled (no AST yet).
Analysis of _thread(CompiledBuiltin) canceled (no AST yet).
Analysis of _stat(CompiledBuiltin) canceled (no AST yet).
Analysis of _abc(CompiledBuiltin) canceled (no AST yet).
Analysis of posix(CompiledBuiltin) canceled (no AST yet).
Analysis of _signal(CompiledBuiltin) canceled (no AST yet).
Analysis of _functools(CompiledBuiltin) canceled (no AST yet).
Analysis of atexit(CompiledBuiltin) canceled (no AST yet).
Analysis of gc(CompiledBuiltin) canceled (no AST yet).
Analysis of _operator(CompiledBuiltin) canceled (no AST yet).
Analysis of _codecs(CompiledBuiltin) canceled (no AST yet).
Analysis of _locale(CompiledBuiltin) canceled (no AST yet).
Analysis of _sre(CompiledBuiltin) canceled (no AST yet).
Analysis of _ast(CompiledBuiltin) canceled (no AST yet).
Analysis of _imp(CompiledBuiltin) canceled (no AST yet).
Analysis of marshal(CompiledBuiltin) canceled (no AST yet).
Analysis of zipimport(CompiledBuiltin) canceled (no AST yet).
Analysis of abc (Stub) on depth 3 completed in 0.23 ms.
Analysis of posix (Stub) on depth 3 completed in 0.3 ms.
Analysis of mmap (Stub) on depth 4 completed in 0.61 ms.
Analysis version 647 has been completed in 0.85 ms with 30 entries analyzed and 446 entries skipped.
IntelliCode identified no likely completion items.
```

## Code Snippet / Additional lnformation
![python bug](https://user-images.githubusercontent.com/8774744/67280921-ebef0680-f4d6-11e9-8cba-f39d759b0765.gif)
```python
m = []
m.
```

**Comment by jakebailey** [comment] 2019-10-22 16:10
Dupe of #1601.

You are on 0.4.72, which has caching enabled (what's causing the bug). You can disable it with:

```
"python.analysis.cachingLevel": "None"
```

https://github.com/microsoft/python-language-server/wiki/Module-caching

**Closed by jakebailey** 2019-10-22 16:10 UTC

**Comment by melkayam92** [comment] 2019-10-22 20:42
@jakebailey Thanks it did fix it.

Another thing - I can't see the "stars" on the autocomplete items anymore - it's related?

**Comment by jakebailey** [comment] 2019-10-22 20:44
The "stars" are IntelliCode, which plugs into the language server and sorts our completion items before we send them to the editor. There shouldn't be anything about caching which changes how they operate, but if they're not showing up I'd check the logs for a message and potentially report an issue on their tracker. A reload may just make it work.
