### ISSUE TITLE
Type of substraction result of datetime and timedelta is not timedelta

### ISSUE THREAD

**Issue by karrtikr** [microsoft/python-language-server#1542] opened 2019-09-13 19:05 UTC
@Kitsunetic commented on [Thu Aug 22 2019](https://github.com/microsoft/vscode-python/issues/7085)

Intellisence recognize the type of (`datetime` - `timedelta`) is `timedelta`

Type of both sum and subtraction operation about `datetime` and `timedelta` is `datetime`
It seems works well if it's add operation but not subtraction operation.

```python
from datetime import datetime, timedelta

now = datetime.utcnow()
time_add = now + timedelta(1) # intellisence thinks it's `datetime`
time_sub = now - timedelta(1) # intellisence thinks it's `timedelta`, but it's `datetime`
```

## Environment data

- VS Code version: 1.37.1
- Extension version (available under the Extensions sidebar): 2019.8.30787
- OS and version: Windows 10 Pro
- Python version (& distribution if applicable, e.g. Anaconda): 3.5.4

---

@karrtikr commented on [Mon Aug 26 2019](https://github.com/microsoft/vscode-python/issues/7085#issuecomment-525028160)

Please inform if you're using Language Server or Jedi, i.e check the value of `python.jediEnabled` in `settings.json`.

**Comment by cdeil** [comment] 2020-05-05 17:43
I see a related bug in the vscode type inference - with Jedi enabled.

Reproducer:
```python
from datetime import datetime, timedelta
now = datetime.utcnow()
future = datetime(2020, 6, 1)
delta = future - now
```

VSCode thinks delta is `datetime.datetime`, but it's a `datetime.timedelta` object.

![Screenshot 2020-05-05 at 19 40 58](https://user-images.githubusercontent.com/852409/81097822-b8227e00-8f08-11ea-8628-52acf2fc9bda.png)

**Comment by cdeil** [comment] 2020-05-05 18:00
Related:
* https://github.com/microsoft/python-language-server/issues/860
* https://twitter.com/ChristophDeil/status/1257730178517733378

@luabud - could you please x-link the issue or PR with the upstream fix in
https://github.com/microsoft/vscode-python/issues/4983 ?
By upstream do you mean Jedi there or Python language server?

**Comment by luabud** [comment] 2020-05-11 19:33
hey @cdeil! 
I updated the comment in microsoft/vscode-python#4983 to the PR that fixed it in the Python Language Server. 
As for the issue with Jedi, I think it should be addressed upstream as well, so I created an issue in the Jedi repo: https://github.com/davidhalter/jedi/issues/1577.

**Comment by davidhalter** [comment] 2020-05-15 22:14
This was fixed in Jedi.

@karrtikr I might be out of the loop, but why did you move the Jedi issue here? Is this language server now also responsible for Jedi related issues? (Because AFAIK this language server is not about Jedi at all).

**Comment by jakebailey** [comment] 2020-05-15 22:17
The original issue was microsoft/vscode-python#7085; this was a bit ago and the original reporter never responded so I think it may have been transferred to us to look into (the assumption being that it was something in this repo). I do not believe this is an issue here either.

**Comment by jakebailey** [comment] 2020-05-15 22:22
Works here:

![image](https://user-images.githubusercontent.com/5341706/82100899-d6823980-96bf-11ea-8b82-364a54f7b040.png)

So I'll close this issue too.

**Closed by jakebailey** 2020-05-15 22:22 UTC
Labels: enhancement, feature: analysis, good first issue

**Comment by karrtikr** [comment] 2020-05-16 08:44
@davidhalter At the time I could reproduce the issue with Language server, which is why I transferred it here. Seems it was fixed with https://github.com/microsoft/python-language-server/pull/1011
