### ISSUE TITLE
Stuck at analyzing in background ...

### ISSUE THREAD

**Issue by kuelumbus** [microsoft/python-language-server#1710] opened 2019-10-21 14:05 UTC
## Environment data

Version: 1.40.0-insider
Commit: 82ca6ba87f450245f665ab7a5f3a686e2cd00045
Date: 2019-10-21T05:33:43.061Z
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-29-generic snap

- Language Server version:  Microsoft Python Language Server version 0.4.72.0   
- OS and version: Ubuntu 16.04
- Python version (& distribution if applicable, e.g. Anaconda): 3.7

## Expected behaviour

Finish analysis

## Actual behaviour

Stuck at "Analyzing in background, 8145 items left ...". Always at item 8145.
![image](https://user-images.githubusercontent.com/44866753/67212542-84f42380-f3ea-11e9-9c3c-4edf713e645c.png)

## Logs

[PLSlog.txt](https://github.com/microsoft/python-language-server/files/3751220/PLSlog.txt)

I assume one of the python packages causes the problem. Any ideas?

**Comment by jakebailey** [comment] 2019-10-21 16:24
Dupe of one of #1502 or #1601.

**Closed by jakebailey** 2019-10-21 16:24 UTC

**Comment by jakebailey** [comment] 2019-10-21 16:26
Try disabling caching.

```
"python.analysis.cachingLevel": "None"
```

**Comment by kuelumbus** [comment] 2019-10-21 19:53
#1601 seems to be the same issue.

> Try disabling caching.
> 
> ```
> "python.analysis.cachingLevel": "None"
> ```
Did help in the beginning but after saving the file or switching to another file it gets stuck again.

BTW, I am using the remote SSH extension.
