### ISSUE TITLE
Request textDocument/hover failed

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#644] opened 2019-02-21 18:31 UTC
@david-waterworth commented on [Wed Feb 20 2019](https://github.com/Microsoft/vscode-python/issues/4476)

## Environment data

- VS Code version: 1.31.0
- Extension version (available under the Extensions sidebar): 2019.1.0
- OS and version: ubuntu 18.04
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.1
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pyenv 

## Expected behaviour
If you create a new file and change language mode to magic python `Output` panel shouldn't fill with error messages when you move the mouse over code before saving the file

## Actual behaviour
If you create a new file and change language mode to magic python `Output` panel fills with error messages when you move the mouse over code before saving the file

## Steps to reproduce:
Ctrl+N to create a new file, change language mode to magic python but __don't save file__. Add code and move mouse over it.

log becomes full of error messages (made worse by an issue I've already submitted resulting in `Output` panel grabbing focus anytime a message is logged to it.

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
Error - 12:12:38 pm] Request textDocument/hover failed.
  Message: unknown document
  Code: -32000 
   at Microsoft.Python.LanguageServer.Implementation.ProjectFiles.GetEntry(Uri documentUri, Boolean throwIfMissing)
   at Microsoft.Python.LanguageServer.Implementation.ProjectFiles.GetEntry(TextDocumentIdentifier document, Nullable`1 expectedVersion, ProjectEntry& entry, PythonAst& tree)
   at Microsoft.Python.LanguageServer.Implementation.Server.Hover(TextDocumentPositionParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Hover(JToken token, CancellationToken cancellationToken)

```

**Comment by jakebailey** [comment] 2019-02-21 18:33
Duplicate of #480.

**Closed by jakebailey** 2019-02-21 18:33 UTC
