### ISSUE TITLE
"Undefined variable: 'e'" in 'except Exception as e:' with MPLS 0.5.30.0

### ISSUE THREAD

**Issue by DonaldKBrown** [microsoft/python-language-server#1907] opened 2020-02-13 17:19 UTC
Issue Type: <b>Bug</b>

With the newest update to VS Code and the Python extension on Ubuntu 20.04, the linter is triggering warnings in the "Problems" tab for perfectly valid code. For example:

`except Exception as e:` is listed as `Undefined variable: 'e'`, despite the `as` statement defining the variable as the Exception object.

Extension version: 2020.2.63072
VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:23.649Z)
OS version: Linux x64 5.4.0-12-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.40GB (0.77GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by meetheed** [comment] 2020-02-14 14:19
im having these problems here as well, not with the e exception specifically but with version 2020.2.63072 throwing up a lot of warnings about undefined variables that i have defined. i can switch back to 2020.1.580.38 and all the warnings are gone, move to version 2020.2.62710 or 2020.2.63072 and i get around 34 warnings. all are in relation to variable being undefined. what i have observed is that the warnings seem to occur if the variables are defined within if statements that may not be true in the current environment. for example i have a piece of code that runs when the platform is linux under an "if sys.platform == 'linux'" check. i then only reference those variables within that same if statement. but VSCs Python extention is now throwing these up as undefined, i can only guess that it is because im running VSC on windows not linux. ive just written a quick example of what i mean. 

`import sys

if sys.platform == 'linux': 
    aVariable="Hello World"
    print(aVariable)`

This code throws a warning that aVariable is not defined on version 2020.2.63072 but does not throw a warning on 2020.1.580.38.

im pretty new to python and VSC. i have tried a clean unstall of VSC and removed all excentions except the "Python" extention. and the problem is there. as i mentioned im on windows 10 and i can use the "install another version" option to install an older version of the python extention which doesnt have this proble.

**Comment by meetheed** [comment] 2020-02-14 14:28
sorry i should have added , the versions i list above are the versions of the Miscoroft Python extention i'm installing. im not sure what version of the MPLS is associated with each version of the extention. Its the only extention i have installed and when i switch extention version i do see a background redownload of the MPLS take place in the status bar.

**Comment by DonaldKBrown** [comment] 2020-02-14 15:02
The issue does not occur on Ubuntu 19.10 (the latest supported release). I could not verify on earlier releases due to missing hardware support in the Linux kernel available on those earlier ones.

Furthermore, the issue no longer occurs using MPLS 0.5.30.0 and Python Extension 2020.2.63072 after completing a kernel upgrade this morning :man_shrugging: . My guess is there was some issue with the pre-release OS I was using.

**Comment by kimadeline** [comment] 2020-02-14 16:26
Thank you for the report @DonaldKBrown, seems like the Linux kernel sometimes operates in ✨ mysterious ✨  ways! Closing the issue as it was OS-related.

@meetheed , please open a separate issue on the [microsoft/vscode-python](https://github.com/microsoft/vscode-python/issues) repo so we can triage it effectively, as it is unrelated to what @DonaldKBrown was experiencing.

**Closed by kimadeline** 2020-02-14 16:26 UTC
