### ISSUE TITLE
Microsoft Intellisense not working with setuptools develop

### ISSUE THREAD

**Issue by stagrovin** [microsoft/python-language-server#1209] opened 2019-06-14 07:46 UTC
It seems not to find the symbols when I "python setup.py develop" on my environment. This occurs with the builtin intellisense engine. Jedi seems to work ok.

## Environment data

- VS Code version: 1.35
- Extension version (available under the Extensions sidebar): 2019.5.18875 
- OS and version: debian 9.9, windows 10
- Python version (& distribution if applicable, e.g. Anaconda): Anaconda w/ python 3.7
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Relevant/affected Python packages and their versions: setuptools
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info #3977): Language Server

## Expected behaviour
When I hover on a symbol, it shows the description.

## Actual behaviour
It shows "Code analysis is in progress..." forever.

## Steps to reproduce:
1. Create a new conda environment with python and setuptools, and activate
2. Write a hello world program in a file main.py
3. Write a setup.py with this contents:
from setuptools import setup 
setup(name='test',
      version='1.0',
      scripts=["main.py"],
      )
3. From terminal, type "python setup.py develop"

## Logs
No output is shown

**Comment by jakebailey** [comment] 2019-06-17 17:28
Does this occur on the daily build?

```json
"python.analysis.downloadChannel": "daily"
```

**Comment by apollo13** [comment] 2019-06-17 18:52
@stagrovin Could you confirm that this is a duplicate of #1175? See my latests comments there for a small reproducer repository.

**Closed** 2019-06-17 19:31 UTC
Labels: bug, editable-installs, feature: imports
