### ISSUE TITLE
High memory usage in 0.3.40(memory leak?)

### ISSUE THREAD

**Issue by CaselIT** [microsoft/python-language-server#1298] opened 2019-07-09 18:45 UTC
The fixed implemented in https://github.com/microsoft/python-language-server/issues/832 worked for some releases, but I'm having again high memory usage problems (10gb+) with version 0.3.20

These seems to be due to a memory leak: if finishes analyzing the project without problems, using less than 1gb in my case. After working on the project for some time it starts using more memory, even more than 10gb+.

I've not kept note of the details regarding after how long or if there is an action that triggers it. I usually notice a slow down, check the task manager and usually the language service is using many gb of memory. I have not kept track to see it the increase in memory usage is sudden or more gradual.

Below are the packages of the project used and some system information. I haven't checked if I can reproduce this issue in other projects

Is there some logging or telemetry I can enable to help with this issue?

Extension version: 2019.6.22090
Microsoft Python Language Server version 0.3.20.0
Python version: 3.6.8
VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>requirements of the project</summary

`argon2_cffi==18.3.0`  
`python-dateutil==2.7.5`  
`decorator==4.3.0`  
`falcon>=2,<3`  
`falcon-auth==1.1.0`  
`falcon-cors==1.1.7`  
`graphene==2.1.3`  
`graphene_sqlalchemy==2.0.0`  
`jsonschema==2.6.0`  
`keras>=2.1.2`  
`numpy>=1.13.3`  
`ortools<7.1 `  
`pandas>=0.22.0,!=0.24.0`  
`psycopg2-binary>=2.7.3.2`  
`psycopg2<2.8`  
`pyjwt>=1.6.4`  
`scikit-learn>=0.19.1`  
`scipy>=1.0.0`  
`SQLAlchemy<1.3.0`  
`SQLAlchemy-Utils>=0.32.21`  
`sqlalchemy-postgres-copy>=0.5.0`  
`simplejson>=3.13.2`  
`tensorflow==1.12.0`  
`pyDOE>=0.3.8`  
`geomdl>=4.1.0`  
`pyomo==5.5.0`  
`pyutilib>=5.6.3`  
`joblib==0.11`  
`pytest>=4.4.0`  
`pytest-cov>=2.6.1`  
`yapf>=0.20.0,!=0.27`  
`flake8>=3.7.0`  
`matplotlib>=2.2.3`  
`waitress==1.1.0`  
`pydot==1.2.4`  

</details>

<details>
<summary>System Info</summary>

![Screen](https://user-images.githubusercontent.com/16175304/60914134-2c5ca880-a289-11e9-9b7c-19facd70c96c.png)

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.84GB (10.36GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/path/to/folder|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by AlexanderSher** [comment] 2019-07-09 18:53
> After working on the project for some time 

How much time have you used it?

**Comment by CaselIT** [comment] 2019-07-09 18:57
Sorry I should have clarified.
I usually notice the issue after 1-4h of the last reload of vscode or kill of the language service.
But I'm estimating here, I have not traked it precisely

**Comment by CaselIT** [comment] 2019-07-09 19:04
I've checked and I still had vscode open after today. Attached is the log from the python output.
[vscode python log.txt](https://github.com/microsoft/python-language-server/files/3374491/vscode.log.txt)
I've killed it at 12, 15:30, then later this evening when I resumed the pc from sleep

**Comment by AlexanderSher** [comment] 2019-07-09 19:16
Ok, thank you!

**Comment by jakebailey** [comment] 2019-07-09 22:14
We just built 0.3.22, which is available in the beta/daily channels. It contains some fixes which we believe will help solve some of the leaks. You can set this and reload to update:

```
"python.analysis.downloadChannel": "beta"
```

**Comment by CaselIT** [comment] 2019-07-10 07:52
I'll try it and report back. Thanks for the quick feedback 👍

**Comment by CaselIT** [comment] 2019-07-10 08:55
I still have the same problem with the 0.3.22.  
This is after about 1h of work.
![image](https://user-images.githubusercontent.com/16175304/60955388-04109080-a301-11e9-871d-c4a09210e2f0.png)

Reinstalling the extension / folder of the language server may help?

**Comment by CaselIT** [comment] 2019-07-10 16:42
I've logged the memory usage with the performance monitor and this is the graph

![image](https://user-images.githubusercontent.com/16175304/60987527-0a732c80-a342-11e9-9827-32224969113c.png)

**Comment by AlexanderSher** [comment] 2019-07-11 18:08
@CaselIT , If you have a venv, can you create `requirements.txt` and attach it to the bug?

**Comment by CaselIT** [comment] 2019-07-11 19:45
Attached is a pip freeze of the current environment.  
I use conda to manage the environments, but I've used pip to install the packages, so all should be there  
[pip freeze.txt](https://github.com/microsoft/python-language-server/files/3383636/pip.freeze.txt)

**Comment by be2112** [comment] 2019-07-12 20:41
I'm noticing the same memory issue.  I'll leave VS Code running for about 1hr and it will end up using 10gb of RAM.

OS Version: Version Windows 10.0.18362.175
Python Version: 2.7.16
VS Code version: 1.36.1

**Comment by jakebailey** [comment] 2019-07-12 20:43
Please try the daily build, which has a few more fixes (mainly #1316).

```
"python.analysis.downloadChannel": "daily"
```

**Comment by dnyaneshgate** [comment] 2019-07-14 19:06
Hi,
Did not see rising memory usage after adding the following line. I kept vscode running for more than 3 hours.
`"python.analysis.downloadChannel": "daily"`

**Comment by MikhailArkhipov** [comment] 2019-07-15 02:52
Closing then.

**Comment by CaselIT** [comment] 2019-07-15 13:52
@MikhailArkhipov I'm still having problems on version 0.3.30.

I'm using "python.analysis.downloadChannel": "daily"

Attached an usage graph collected from the performance monitor. I've also added the cpu usage (in blue) to the graph, since it seems correlated with the memory increase  
Note that from about 12 -> 14:30 I was now working in vscode, but had it still open.
![image](https://user-images.githubusercontent.com/16175304/61221112-0e26fa80-a718-11e9-885f-6e71a72c19ad.png)

I can share the raw data from the performance monitor if it may be useful.

**Comment by CaselIT** [comment] 2019-07-16 11:23
I've tried also with today's dayly, version 0.3.36
![image](https://user-images.githubusercontent.com/16175304/61290733-df1e9080-a7cc-11e9-973f-44f342d085c9.png)

@MikhailArkhipov can you reopen the issue? Thanks

**Comment by CaselIT** [comment] 2019-07-16 14:34
Is there some documentation on how I can profile the memory used by the language server?

Sadly, I cannot share the project I'm working on, but I would like to help solve this if I can

**Comment by MikhailArkhipov** [comment] 2019-07-16 16:18
There are tools in Visual Studio (Analyze menu) as well as in Debug | Windows | Show Diagnostic Tools
![image](https://user-images.githubusercontent.com/12820357/61311102-8211e300-a7aa-11e9-89c7-8e414201169b.png). https://memprofiler.com/ is very good, I guess you can try trial version.

**Comment by MikhailArkhipov** [comment] 2019-07-16 16:23
Actually we don't necessary need your project. Issue may be in some large library you may be importing so list of common imported and installed packages and type of environment (regular, virtual, Anaconda). No need to publish private pieces.

**Comment by CaselIT** [comment] 2019-07-16 18:42
Thanks for the advice, I'll try to profile the memory tomorrow.

I've shared the all the packages I have in the environment in this comment https://github.com/microsoft/python-language-server/issues/1298#issuecomment-510627528 above. I don't think my project can be considered large, since it's less than 20k loc

**Comment by CaselIT** [comment] 2019-07-17 12:24
Attached is a profiler session file that can be opened with https://memprofiler.com/
[ms.python.ls.prfsession.zip](https://github.com/microsoft/python-language-server/files/3401799/ms.python.ls.prfsession.zip)
I've obtained it using `NmpCore.exe /da <process id>`  from https://memprofiler.com/nmpcore

I don't know how to properly use the tool, but it seems most of the memory falls in the category unused overhead
![image](https://user-images.githubusercontent.com/16175304/61375110-5708bb80-a89e-11e9-9e00-ed818acc825b.png)

I hope in helps solving this

**Comment by jppellerin** [comment] 2019-07-17 13:03
I am having similar memory issues, but only when I add a path in my settings `python.autoComplete.extraPaths`.  Removing values there and I no longer get high meomry consuption.  Mind you, this is required for adequate intellisense for my current application.

![image](https://user-images.githubusercontent.com/4185657/61377672-ac7aa380-a871-11e9-8cd5-5f6d070d0e03.png)

**Comment by CaselIT** [comment] 2019-07-17 13:24
I'm not using `python.autoComplete.extraPaths`

**Comment by AlexanderSher** [comment] 2019-07-17 16:55
@CaselIT, do you have any big files in your repo? 50kb or larger?

**Comment by MikhailArkhipov** [comment] 2019-07-17 17:25
@jppellerin - since cases may be different, please open separate issue and provide extra path settings. List of imported packages would help too. Thanks.

**Comment by CaselIT** [comment] 2019-07-17 19:34
> @CaselIT, do you have any big files in your repo? 50kb or larger?

I do have some, 3 above 50k, ~57K ~72k and ~77k. They are all less than 2k loc

**Comment by juliotux** [comment] 2019-07-19 02:12
Also confirmed for running on Linux.
![Screenshot from 2019-07-18 23:04:36](https://user-images.githubusercontent.com/497246/61504187-ddadbd80-a9b0-11e9-952f-54c930274851.png)

In status bar, the message `Analyzing in backgroung, XXXX items left...` do not end and the items count restarts very often.

**Comment by juliotux** [comment] 2019-07-22 18:17
Only one more small comment about the memory leaking behavior. It seems to happen right after I reinstall the package I'm working with `pip`. After reinstall, the LS seems to re-analyze everything, but not freeing the old analysis.

**Comment by jakebailey** [comment] 2019-07-22 18:43
That's an interesting lead; I'll look now. I recently fixed our package install detection mechanism (it hadn't been working at all), so maybe that's it and some reference to the removed analysis is the issue.

**Comment by CaselIT** [comment] 2019-07-22 19:00
I have not noticed this. I have not changed the installed packaged recently. The environment that I use is not the default one though. The python exe path is set in the workspace setting. May it be correlated?

**Comment by jakebailey** [comment] 2019-07-22 19:05
As far as I can tell, we don't actually drop things from memory on uninstall like we should, so that's something to look into (but could be worked around by restarting the editor), but that likely is not going to be the root cause of the other issues where a project is just opened and uses too much memory.

For consistency, @juliotux make sure you're on the latest build 0.3.38 (which you probably are).

I haven't yet been able to reproduce the memory usage issue with my typical large projects. And to be clear, "large projects" doesn't really have anything to do with the size of the user code; these sorts of memory issues almost always come from a very large set of dependencies. I can have a one-line piece of code like `import pandas` and that use a lot of memory (because there's a lot in that graph).

**Comment by CaselIT** [comment] 2019-07-22 19:12
I currently have no complaint about the loaded memory usage, it's about 350mb for the project in question, as shown in the profiling screenshot above. The problem is that over time it grows to 10+ gb.

I'm not 100% certain, but I've noticed that the memory does not increase on its own, ie if you leave vscode open but do not interact with it, because you are doing something else, the memory will not increase. Again, it's just something I've notices, but I have not done rigorous testing on it

**Comment by juliotux** [comment] 2019-07-22 19:14
> For consistency, @juliotux make sure you're on the latest build 0.3.38 (which you probably are).

Yes @jakebailey
```[Info  - 3:09:39 PM] Microsoft Python Language Server version 0.3.38.0```

**Comment by juliotux** [comment] 2019-07-22 19:19
> I've tried also with today's dayly, version 0.3.36
> ![image](https://user-images.githubusercontent.com/16175304/61290733-df1e9080-a7cc-11e9-973f-44f342d085c9.png)

@CaselIT when you generated these gaphs, did you make something specific during these peaks of processor usage? Analyzing your graphs and the behavior of my LS, it looks like the memory leak only occurs when, by some reason, the LS restarts the analyzis of the project and the entire list of dependencies.

**Comment by CaselIT** [comment] 2019-07-22 19:28
Nothing particular that I remember, just usual coding. I have notices that changing git branch will restart the language server, but I don't think to have changed branch or done something else git related during that recording.

I usually use another git worktree if I need to check something on a different branch

**Comment by jakebailey** [comment] 2019-07-22 19:31
Changing git branches is definitely going to lead to bad results (though theoretically not memory issues); the editor doesn't send us change events for unopened files and we wouldn't have any idea that a piece of user code was changed under the hood. AFAIK the common thing with language servers is to tell people to do reloads if that occurs, but I might be mistaken.

**Comment by jakebailey** [comment] 2019-07-22 22:08
@CaselIT I'm looking at the profile you captured and am seeing the same thing. Almost all of the memory is listed as "unused" heap, which I believe is memory that the .NET runtime has retained for future used but has not yet released to the operating system.

Does the machine you captured that profile on have a large amount of memory?

If it's really just large heap free space not being released, I'm not sure what all we can do; As far as I can tell the runtime uses a bunch of rules for deciding if it should release that memory back, including something like "if the machine has a lot of RAM free, don't release any back". We already do heap compaction after large analysis sessions, but small once would never cause a compact and could also increase memory usage due to fragmentation.

**Comment by CaselIT** [comment] 2019-07-22 22:28
>Does the machine you captured that profile on have a large amount of memory?

Not really, it has 24gb of ram. it usually has 90%+ of ram used when the language server is using 10gb of ram. I have the swap space that is system managed on a 1tb ssd that is about 1/4 full, so it may increase quite a bit, but I don't think it would count toward the ram size

**Comment by AlexanderSher** [comment] 2019-07-23 06:36
@CaselIT, can I ask you to attach WinDBG to your process to verify if we have a case of LOH memory fragmentation? Here is an article on how to do it: https://vimvq1987.com/exploring-large-object-heap-windbg/

**Comment by ofek** [comment] 2019-07-24 00:09
I've been experiencing this as well starting a few days ago

![Capture](https://user-images.githubusercontent.com/9677399/61755496-c8a4a600-ad85-11e9-8184-8c6c46d0500a.PNG)

**Comment by CaselIT** [comment] 2019-07-24 18:58
@AlexanderSher I've installed windbg and read the article.
Other than ` !eeheap -gc`, is there some other command I can run to aid in solving this?

**Comment by AlexanderSher** [comment] 2019-07-24 19:24
@CaselIT, can you share the output from ‘!dumpheap <Starting address of LOH>’?

**Comment by CaselIT** [comment] 2019-07-24 19:58
I've only got the dump from today that was about 1.1gb. (I've worked mainly on other projects in the last few days).
This is the output of `!dumpheap -stat [Starting address of LOH]` [dupheap stas.txt](https://github.com/microsoft/python-language-server/files/3428552/dupheap.stas.txt)

The one without stat is still logging

**Comment by CaselIT** [comment] 2019-07-24 21:36
>The one without stat is still logging

I've stopped it after more than 1h. The log file is 500+mb  
Let me know if the full output is needed.
I'll try to rerun the command when the ls uses more memory

**Comment by schwab** [comment] 2019-07-25 03:55
This issue is getting pretty serious. In my case opening a project for ~ an hour is enough to bring the system to it's knees.  A couple hours and all the memory including swap gets used and the machine starts to lock up.  
![Screenshot from 2019-07-24 22-45-47](https://user-images.githubusercontent.com/1517342/61844488-3bd11980-ae65-11e9-9dd7-b59fb1bd4e74.png)
This particular project has just 635 files but the analyzing message in the status bar is almost always running and never really completes.  Many times it has 3-4 thousand files to analyze which means it must be going well beyond the projects's folder.  Also they appear to be constantly re-scanned even when no files are being edited or changed.

**Comment by schwab** [comment] 2019-07-25 03:59
Note: setting debug configuration "justMyCode" :true  reduces the problem substantially, however that also prevents debugging installed modules even those that are a part of the project's build.

**Comment by CaselIT** [comment] 2019-07-25 11:16
Here is an updated output with a dump of 5.2gb.
It has two large object heap so there are two `!dumpheap` outputs.
[dupheap stas.5.2gb.txt](https://github.com/microsoft/python-language-server/files/3431217/dupheap.stas.5.2gb.txt)

Let me know if there is something else that can help solving this

**Comment by schwab** [comment] 2019-07-25 11:46
Realizing that justMyCode:true fixes the problem led me to look closely at my installed packages.  Then I found that my .../python3.6/site-packages folder had > 200 versions of my project's package library installed.  In dev, each time I build a new version, my build script installs that version on the local system.  This, over time has led to hundreds of installed versions since they are never automatically uninstalled.  So I pip3 uninstall[ed] them until they were all gone and then installed just one copy of the latest version.  Now I can run debugging with justMyCode:false and  I'm not seeing high cpu or memory usage of the language server any longer.  I'm not sure this the only way to reproduce the problem, but maybe it will help someone else to know about this.
![Screenshot from 2019-07-25 06-45-02](https://user-images.githubusercontent.com/1517342/61871979-cb97b780-aea7-11e9-9ad0-5ffb151e2d66.png)

**Comment by CaselIT** [comment] 2019-07-25 11:54
@schwab i'm not installing the package I'm developing, so I don't think it will have an impact, but I'll try setting ` "justMyCode" :true`

**Comment by CaselIT** [comment] 2019-07-25 12:20
I've just thought of something, not sure if it may be related. I use imports only for the typing in an `if False:` block since it would cause a circular reference if imported normally. Example:
```py
if False:
    # import the type but avoid circular references
    from .somefile import SomeType
...
def someFunction(foo: 'SomeType'):
    ....
```
The typing is correctly picked up by vscode, so I think the language server support this, but maybe the circular reference causes some problems?

**Comment by AlexanderSher** [comment] 2019-07-25 14:22
@CaselIT , @schwab - thank you guys very much for helping us with this issue.

> This is the output of `!dumpheap -stat [Starting address of LOH]`

It looks like you've mistyped the address. It should've been `!dumpheap -stat 0x000001da10001000`, not `!dumpheap -stat 000001da10001000`. This probably explains why it took so long to run `!dumpheap [Starting address of LOH]`.

On the other hand, your logs show that version of LS that is installed on your machine has another type of leak: there are 2 millions variables for just 500 modules.

**Comment by CaselIT** [comment] 2019-07-25 15:39
@AlexanderSher I've tried using `0x...` and the result of `-stat` is the same. I'm using the windbg preview from the [store](https://www.microsoft.com/it-it/p/windbg-preview/9pgjgd53tn86?rtc=1&activetab=pivot:overviewtab)

>version of LS that is installed on your machine

Current version is `Microsoft Python Language Server version 0.3.40.0`. This is for sure the version of the second log, the one with 5.2gb. I did not check the version I had yesterday for the other log, the one with 1.1gb, but I think it's the same version.

**Comment by jakebailey** [comment] 2019-07-25 16:12
@schwab For what it's worth, `justMyCode` is a debugger option; the language server never reads it or uses it in any way.

**Comment by jakebailey** [comment] 2019-08-05 22:42
We just built 0.3.46 to the beta/daily channels with a fix for when modules get reloaded (among other potential fixes), if you'd like to retry. (@juliotux since you had pointed out the pip issues.)

**Comment by jakebailey** [comment] 2019-08-05 22:50
#1407 may also be a source of some leaks, but I'd think only a small contribution.

**Comment by frankli0324** [comment] 2019-08-06 16:21
I think it makes sense to persist some analyzing work into some static file and deliver them with the plugin?

**Comment by MikhailArkhipov** [comment] 2019-08-06 16:22
I does, ongoing work in https://github.com/microsoft/python-language-server/issues/472. But leak is a leak and before static storage is created regular analysis needs to run.

**Comment by frankli0324** [comment] 2019-08-06 16:24
wow...... that's a faaast reply.... great thing to know, thanks!

**Comment by CaselIT** [comment] 2019-08-06 20:35
Thanks for the updates

> We just built 0.3.46 to the beta/daily channels

I'm no holiday at the moment, when I get back I'll try it and report back

**Comment by juliotux** [comment] 2019-08-10 18:15
On 0.3.46 the leaking behavior seems to be solved. Now, the LS reaches around 1GB while analyzing the files, and after it, it drops to around 400 MB. Multiple `pip install` of the project do not accumulate memory as before, getting exactly the same memory behavior every install cycle.

**Comment by CaselIT** [comment] 2019-09-04 10:06
Sorry for the long absence, but I've been on holiday and then had to work on another project for a bit.

This week I've returned to work to the project that has been causing problems, and I still have large memory issues.

This is a dump from `Microsoft Python Language Server version 0.3.72.0` with a size of ~6gb
[dupheap stas.5.9gb.txt](https://github.com/microsoft/python-language-server/files/3573955/dupheap.stas.5.9gb.txt)

I'm not been tracking its memory usage but I've noticed that sometimes its memory usage decreases: a few minutes before dumping the memory to collect the stats the language server was using ~8gb, so some progress seem there seems to have happened.

Hope it helps. I can track its memory usage it may help

**Comment by CaselIT** [comment] 2019-10-19 10:28
Just a follow up.

I'm currently working on the [sqlalchemy library](https://github.com/sqlalchemy/sqlalchemy) so I have it installed in editable mode with pip (`pip install -e .` in the sqlalchemy folder) and after about 1h of working on it, mainly navigating between classes, the language server is at about 4.3 GB or used ram. I'm on Version 0.4.71.0

I was using sqlalchemy also on my original project. I still cannot trigger it on demand, but at least this is now happening on an open source project, so it may be easier to reproduce

I'm using a env only for this, so the packages installed are not that many:

<details>
<summary> Packages </summary>

<pre>
Package            Version      Location                                         
------------------ ------------ -------------------------------------------------
apipkg             1.5          
appdirs            1.4.3        
asn1crypto         1.2.0        
atomicwrites       1.3.0        
attrs              19.2.0       
backcall           0.1.0        
black              19.3b0       
bleach             3.1.0        
certifi            2019.9.11    
cffi               1.13.0       
Click              7.0          
colorama           0.4.1        
cryptography       2.7          
decorator          4.4.0        
defusedxml         0.6.0        
entrypoints        0.3          
execnet            1.7.1        
importlib-metadata 0.23         
ipykernel          5.1.2        
ipython            7.8.0        
ipython-genutils   0.2.0        
jedi               0.15.1       
Jinja2             2.10.3       
json5              0.8.5        
jsonschema         3.0.2        
jupyter-client     5.3.3        
jupyter-core       4.5.0        
jupyterlab         1.1.4        
jupyterlab-server  1.0.6        
MarkupSafe         1.1.1        
mistune            0.8.4        
mock               3.0.5        
more-itertools     7.2.0        
nbconvert          5.6.0        
nbformat           4.4.0        
notebook           6.0.1        
packaging          19.2         
pandocfilters      1.4.2        
parso              0.5.1        
pickleshare        0.7.5        
pip                19.2.3       
pluggy             0.13.0       
prometheus-client  0.7.1        
prompt-toolkit     2.0.10       
psycopg2           2.8.3        
py                 1.8.0        
pycparser          2.19         
Pygments           2.4.2        
PyMySQL            0.9.3        
pyparsing          2.4.2        
pyrsistent         0.15.4       
pytest             5.2.1        
pytest-forked      1.0.2        
pytest-xdist       1.30.0       
python-dateutil    2.8.0        
pywin32            225          
pywinpty           0.5.5        
pyzmq              18.1.0       
Send2Trash         1.5.0        
setuptools         41.4.0       
six                1.12.0       
SQLAlchemy         1.4.0b1.dev0 c:\<my folder>\sqlalchemy\lib
terminado          0.8.2        
testpath           0.4.2        
toml               0.10.0       
tornado            6.0.3        
traitlets          4.3.3        
wcwidth            0.1.7        
webencodings       0.5.1        
wheel              0.33.6       
wincertstore       0.2          
zipp               0.6.0        
</pre>

</details>

**Comment by MikhailArkhipov** [comment] 2019-12-16 21:48
Cloning and opening `sqlalchemy` as a workspace yielded ~500MB RAM consumption.

**Comment by CaselIT** [comment] 2019-12-16 22:22
Since version 0.5 I don't seem to notice overly large memory usage, sometimes I've seen a couple of GB, but I have not had to kill the language server for it. I'm not monitoring it closely though

I'm not sure if the underling issue has been solved or not, but I think this can be closed for now. If I notice again the same high usage I'll reopen it (or a new one)

**Comment by MikhailArkhipov** [comment] 2019-12-16 22:24
Thanks! 2GB is high-ish, but with large libraries sometimes happens during peak consumption which should be released when analysis is done.

**Closed by MikhailArkhipov** 2019-12-16 22:24 UTC
Labels: bug, memory size

**Comment by CaselIT** [comment] 2019-12-16 22:26
Thanks for the improvements your team have doing to the language server 👍
