### ISSUE TITLE
Error in "Go to Definition" in WSL. ENOTDIR: not a directory

### ISSUE THREAD

**Issue by arqeco** [microsoft/python-language-server#1920] opened 2020-02-25 19:00 UTC
When a folder is opened using File > Open Folder, the "Go to Definition" works fine.

But when the same folder is opened using VS Code Remote WSL there is an error when trying to use "Go to Definition":

`
Unable to open 'visor.py': Unable to read file 'vscode-remote://wsl+ubuntu-18.04/home/client/visor.py/home/client/visor.py' (Unknown (FileSystemError): Error: ENOTDIR: not a directory, stat '/home/client/visor.py/home/client/visor.py').
`

The path seems duplicated in the error message.

## Environment data

- VS Code version: 1.42.1
- ms-vscode-remote.remote-wsl 1.809.610
- OS and version: Windows 10 version 1903
- Python 3.8.0
- Type of virtual environment used: venv

**Comment by jakebailey** [comment] 2020-02-26 17:47
This looks like a dupe of #1687. Same error and doubling of paths. Likely due to the `+` in the URI (may need to rework escaping), but I'm unsure past that.

**Closed** 2020-02-26 17:47 UTC
Labels: duplicate
