### ISSUE TITLE
Django autocomplete

### ISSUE THREAD

**Issue by spinelsun** [microsoft/python-language-server#2106] opened 2020-07-21 12:38 UTC
Hi,

I am developing with django and my autocomplete doesn't work on models object (e.g if my model is User, User.objects.create is not autocompleted).
Is there a way to make it work?

**Comment by jakebailey** [comment] 2020-07-21 17:28
Duplicate of #129.

But you may want to try [Pylance](https://devblogs.microsoft.com/python/announcing-pylance-fast-feature-rich-language-support-for-python-in-visual-studio-code/), which includes some Django type stubs.

**Closed by jakebailey** 2020-07-21 17:28 UTC
Labels: question
