### ISSUE TITLE
Problem hinting surfaces False Positives (abbreviated characters for symbol)

### ISSUE THREAD

**Issue by karrtikr** [Microsoft/python-language-server#626] opened 2019-02-19 18:30 UTC
@sutt commented on [Sat Feb 16 2019](https://github.com/Microsoft/vscode-python/issues/4427)

## Environment data

- VS Code version: 1.31.1
- Extension version (available under the Extensions sidebar): ms-python.python (2018.12.1)
- OS and version: win10 1803 (17134.590)
- Python version (& distribution if applicable, e.g. Anaconda): python 2.7.13 32bit/win32
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): n/a
- Relevant/affected Python packages and their versions: n/a

## Expected behaviour

This is a tough bug to describe and document. I'm putting one example here and intend to add more examples as they come up. If anyone else has this problem that would be helpful)
Before I updated to v 2019.1 then rolled-back to 2018.12.1 (due to https://github.com/Microsoft/vscode-python/issues/4223) I did not see these errors; the language server worked as expected.

## Actual behaviour

Here's the language server not recognizing 'continue' as a keyword. [Note: 'continue' or any other keyword is not the scope of the problem, this happens when say defining myList=[] then a few lines later doing myList.append(...]
![image](https://user-images.githubusercontent.com/2819112/52902077-b53f4e80-31d9-11e9-8051-0a3c0152a918.png)

Here's the big part of the bug, the language server is not getting all characters for the keyword/symbol that has been typed into the editor. As can be seen here: the language server thinks I've only typed 'continu' instead of 'continue'
![image](https://user-images.githubusercontent.com/2819112/52902159-14519300-31db-11e9-8f23-88a87d54caf2.png)

This isn't just typing "lag" the problem will sometimes remain active indefinetly (until I perform the workarounds listed below), other times it will clear in ~3 seconds. Here's the problem stuck in the Problems panel:
![image](https://user-images.githubusercontent.com/2819112/52902218-0f411380-31dc-11e9-8916-242b2681427a.png)

I can get the errors to clear by hitting Ctrl+Enter on the line they are present. Or by restarting vscode.

## Steps to reproduce:
1. hard to say, 90% it works as expected, randomly it fails.

**Comment by jakebailey** [comment] 2019-02-19 18:37
This seems like a duplicate of #386. The new LS has a completely rewritten diagnostics system, so this may just go away when we release it.

**Comment by MikhailArkhipov** [comment] 2019-03-01 18:17
This is no longer happening in new LS.

**Closed by MikhailArkhipov** 2019-03-01 18:17 UTC
