### ISSUE TITLE
False Positive Warning: "Inheriting 'Protocol', which is not a class."

### ISSUE THREAD

**Issue by jordan-schneider** [microsoft/python-language-server#2091] opened 2020-06-26 16:50 UTC
## Environment data

- Language Server version:  0.5.50.0
- OS and version: Ubuntu 19,10
- Python version (& distribution if applicable, e.g. Anaconda): conda 3.7.6

## Expected behaviour

No warning raised on

```python
from typing_extensions import Protocol

class Proto(Protocol):
    ...
```

## Actual behaviour

"Inheriting 'Protocol', which is not a class." warning is raised

## Logs

```
Analysis of safe_runner (User) queued. Dependencies: logging, collections, dataclasses, itertools, math, gym, numpy, torch, typing_extensions, estimates.model_learning, line_search.log_search, rl_types, rlpyt.agents.base, rlpyt.algos.base, rlpyt.runners.minibatch_rl, rlpyt.samplers.base, rlpyt.samplers.collections, rlpyt.utils.logging, rlpyt.utils.logging.logger, utils.probability, utils.rlpyt, utils.torch, utils.trajectory, utils.trajectory_builder
Analysis version 7167 of 1 entries has started.
Analysis of safe_runner (User) on depth 0 completed in 8.16 ms.
Analysis version 7167 of 1 entries has been completed in 8.45 ms.
Analysis of safe_runner (User) queued. Dependencies: logging, collections, dataclasses, itertools, math, gym, numpy, torch, typing_extensions, estimates.model_learning, line_search.log_search, rl_types, rlpyt.agents.base, rlpyt.algos.base, rlpyt.runners.minibatch_rl, rlpyt.samplers.base, rlpyt.samplers.collections, rlpyt.utils.logging, rlpyt.utils.logging.logger, utils.probability, utils.rlpyt, utils.torch, utils.trajectory, utils.trajectory_builder
Analysis version 7168 of 1 entries has started.
Analysis of safe_runner (User) on depth 0 completed in 14.19 ms.
Analysis version 7168 of 1 entries has been completed in 14.52 ms
```

**Comment by jakebailey** [comment] 2020-06-26 19:41
Dupe of #2021; will need #535.

**Closed by jakebailey** 2020-06-26 19:41 UTC
