### ISSUE TITLE
IntelliSense for Pandas df.plot() doesn't show up

### ISSUE THREAD

**Issue by eisber** [microsoft/python-language-server#1759] opened 2019-11-05 21:37 UTC
## Environment data

Version: 1.40.0-insider (user setup)
Commit: 515f496d9a7617caf07f38298f610920f60834d6
Date: 2019-11-05T14:32:05.211Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
- Extension version (available under the Extensions sidebar): XXX
- Python version: minicodna3
- Type of virtual environment used: virtualenv 
- Relevant/affected Python packages and their versions: Pandas

## Expected behaviour

Show documentation for plot

## Actual behaviour

Nothing happens

## Steps to reproduce:

```python
import pandas as pd
from urllib.request import urlretrieve

iris = 'http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
urlretrieve(iris)

df = pd.read_csv(iris, sep=',')

attributes = ["sepal_length", "sepal_width", "petal_length", "petal_width", "class"]
df.columns = attributes

df.plot()
```

## Logs
Python language server output is empty.

**Comment by jakebailey** [comment] 2019-11-06 17:39
Likely duplicate of #981. What do you get when you hover over `df`?

**Comment by eisber** [comment] 2019-11-06 21:28
Nothing.

**Comment by jakebailey** [comment] 2019-11-06 22:39
Thanks for checking. Do things work out if you annotate the variable, i.e. write:

```python
df: pd.DataFrame = pd.read_csv(iris, sep=',')
```

**Comment by eisber** [comment] 2019-11-07 00:09
After restarting my VSCode instance, getting the latest updates and waiting patiently for the code analysis to be finished (I got a progress report in the status bar) it actually started to work.

**Comment by jakebailey** [comment] 2019-11-07 00:14
I see, since this issue was transferred to our repo I should have asked for the LS version you had. Since you're on the insiders build, you may have been on a version before some recent fixes (and restarting triggered the extension to update it's copy of the LS). If you look at the Python Language Server output window, what version are you seeing printed at the top?

**Comment by eisber** [comment] 2019-11-07 01:48
Microsoft Python Language Server version 0.4.99.0

**Comment by jakebailey** [comment] 2019-11-07 17:36
And this version is working for you, once the analysis completes?

**Comment by eisber** [comment] 2019-11-07 19:14
yes it does. I'll close the issue?

**Comment by jakebailey** [comment] 2019-11-07 19:21
Thanks for confirming. We'll be releasing this updated version to the stable build when the next VS Code extension version is released.

**Closed by jakebailey** 2019-11-07 19:21 UTC
