### ISSUE TITLE
Failure analyzing decorator module, high CPU/RAM usage

### ISSUE THREAD

**Issue by uriva** [microsoft/python-language-server#1401] opened 2019-08-02 18:55 UTC
Hi,

I have `"python.jediEnabled": false` in my `settings.json`.

Whenever I open a project, I see "analyzing in background" for a bit, then it stops. Usually it's 1200 targets or something similar.

Then from time to time I have a spike of cpu (200%) and ram usage from the process, and the code is again "analyzed in background".

This is coming from `.vscode/extensions/ms-python.python-2019.6.24221/languageServer.0.3.43/Microsoft.Python.LanguageServer`.

Over the last month the cpu/ram issues were on and off. At first they were making the computer stuck (I had to restart) and other times it went away after awhile. I saw some issues were opened and the closed, but over the last two weeks it again became hard to work with vscode because of this, so probably the problem isn't completely fixed.

**Comment by MikhailArkhipov** [comment] 2019-08-02 19:05
Could you provide
- Amount of RAM used (few hundred meg is not unusual)
- List of packages you use beside system (i.e. tensorflow, numpy, plotly?)
- How long CPU spike may last (LS is heavily multi-threaded so using multiple cores is normal unless it lasts for a long time).

**Comment by uriva** [comment] 2019-08-02 19:16
I can't easily reproduce, but an hour ago I edited some code and it seems to re-analyze on every code change, then the entire cpu is unresponsive and I have to power down, so it's more than a few hundred megs.

Now by just opening the project and waiting for awhile, it reaches 6GB ram consumption.

I think spacy and selenium are the heaviest dependencies I have (no tensorflow).

**Comment by uriva** [comment] 2019-08-02 19:17
Another thing that may be of interest is that I have two projects opened sometimes, and one depends on the other (pip install -e).

**Comment by uriva** [comment] 2019-08-02 19:19
I think the cpu is less of a worry than ram is (makes the mouse unusable).

**Comment by jakebailey** [comment] 2019-08-02 19:20
If they depend on each other and you open them separately, then you'll have two language servers running watching both such that changing one causes the other to be reanalyzed. If that's happening often, then this may be the module reloading memory usage issue I'm currently working on.

**Comment by uriva** [comment] 2019-08-02 19:21
Now for example it's analyzing >5 minutes, and the computer intermittently freezes.

**Comment by uriva** [comment] 2019-08-02 19:23
@jakebailey I think this is related, as it's aggravated when I'm working on the two projects at the same time, but it's not explaining the very long analysis even when there's no code change.

**Comment by uriva** [comment] 2019-08-08 13:57
I'm also using ipython with autoreload in case it matters.

**Comment by jakebailey** [comment] 2019-08-08 16:50
Can you retest things with the latest version? 0.3.46 contains a memory fix to module reloading (and others), which appears to have restored things to as they were a few weeks ago.

**Comment by uriva** [comment] 2019-08-10 12:35
There's definitely an improvement, but still not as it was >1 month ago.

Still any code change in the dependency project causes a spike (I measured 2GB now). And high cpu.

This is tolerable, but I did manage to reach a state where again analysis never ends, but was not able to repro/measure ram, so will update once it happens again.

**Comment by uriva** [comment] 2019-08-10 22:05
Sadly after a few edits in the dependency project, analysis starts again and is stuck on the same number (e.g. 1000 items) infinitely. Ram is rising to 5.5g (+ 11g in virtual memory) and the computer becomes unresponsive.

**Comment by jakebailey** [comment] 2019-08-12 17:08
I'd appreciate it if you enable trace logging and upload a copy of the language server logs when this happens. See here for some info: https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#filing-an-issue

**Comment by uriva** [comment] 2019-08-13 07:32
okay (I did some small redactions for privacy) https://gist.github.com/uriva/a0f243c8b15a03c264afc6a2ae27a936

Reproduction is just to do several changes across different files in the dependency project. Then it goes into infinite analysis. You can see that some lines are repeating thousands of times.
This run never ends actually (>>10 minutes), the pc is "usable", but working very hard the entire time (as I said before, sometimes it is even worse, and the pc becomes unresponsive).

**Comment by jakebailey** [comment] 2019-08-13 17:21
This looks similar to #1426, actually. I see `decorator` is failing. In the same environment, can you open a file that's just `import decorator`, and see if you see an exception come up when doing something like `decorator.` to trigger completion on the module?

**Comment by uriva** [comment] 2019-08-13 22:16
Seems to be working fine when writing `decorator.` suggestions come up normally.

**Comment by uriva** [comment] 2019-08-14 10:13
Actually you're right, I don't know why I haven't seen it before.

There are 17 lines related to decorator in scipy:

>Analysis of scipy._lib.decorator(Library) failed. Exception message: Object reference not set to an instance of an object..

And another 17 related to just decorator:

>Analysis of decorator(Library) failed. Exception message: Object reference not set to an instance of an object..

Also a bunch of missing keys messages if it matters.

**Comment by jakebailey** [comment] 2019-08-14 16:44
Could you also try importing `scipy._lib.decorator` and doing `decorator.` on that? Essentially, I'm trying to get the exception to print itself; those exceptions during the analysis don't have their stack trace printed (which should probably be fixed).

**Comment by jakebailey** [comment] 2019-08-14 19:40
We just built a version which includes some more logging. I'd appreciate it if you could set the following in your config and reload to trigger a download, then see if you can grab one of the stack traces for those exceptions.

```json
"python.analysis.downloadChannel": "daily"
```

**Comment by Coderx7** [comment] 2019-08-15 04:03
Here is my log after adding  : 
`"python.analysis.downloadChannel": "daily"`
[log file](https://we.tl/t-N234OMekK0)

**Comment by jakebailey** [comment] 2019-08-15 05:49
The relevent bits:

```
Analysis of decorator(Library) failed. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Python.Analysis.Analyzer.Symbols.FunctionEvaluator.Walk(ReturnStatement node) in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\Symbols\FunctionEvaluator.cs:line 122
   at Microsoft.Python.Parsing.Ast.ReturnStatement.Walk(PythonWalker walker) in E:\A\_work\3\s\src\Parsing\Impl\Ast\ReturnStatement.cs:line 34
   at Microsoft.Python.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker) in E:\A\_work\3\s\src\Parsing\Impl\Ast\SuiteStatement.cs:line 41
   at Microsoft.Python.Analysis.Analyzer.Symbols.FunctionEvaluator.Evaluate() in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\Symbols\FunctionEvaluator.cs:line 64
   at Microsoft.Python.Analysis.Analyzer.Symbols.ModuleSymbolTable.Evaluate(ScopeStatement target) in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\Symbols\ModuleSymbolTable.cs:line 87
   at Microsoft.Python.Analysis.Analyzer.ModuleWalker.Walk(FunctionDefinition node) in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\ModuleWalker.cs:line 189
   at Microsoft.Python.Parsing.Ast.FunctionDefinition.Walk(PythonWalker walker) in E:\A\_work\3\s\src\Parsing\Impl\Ast\FunctionDefinition.cs:line 197
   at Microsoft.Python.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker) in E:\A\_work\3\s\src\Parsing\Impl\Ast\SuiteStatement.cs:line 41
   at Microsoft.Python.Parsing.Ast.IfStatementTest.Walk(PythonWalker walker) in E:\A\_work\3\s\src\Parsing\Impl\Ast\IfStatementTest.cs:line 41
   at Microsoft.Python.Parsing.Ast.IfStatement.Walk(PythonWalker walker) in E:\A\_work\3\s\src\Parsing\Impl\Ast\IfStatement.cs:line 45
   at Microsoft.Python.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker) in E:\A\_work\3\s\src\Parsing\Impl\Ast\SuiteStatement.cs:line 41
   at Microsoft.Python.Parsing.Ast.PythonAst.Walk(PythonWalker walker) in E:\A\_work\3\s\src\Parsing\Impl\Ast\PythonAst.cs:line 81
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerSession.AnalyzeEntry(IDependencyChainNode`1 node, PythonAnalyzerEntry entry, IPythonModule module, PythonAst ast, Int32 version) in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\PythonAnalyzerSession.cs:line 326
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerSession.Analyze(IDependencyChainNode`1 node, AsyncCountdownEvent ace, Stopwatch stopWatch) in E:\A\_work\3\s\src\Analysis\Ast\Impl\Analyzer\PythonAnalyzerSession.cs:line 264
```

cc @CTrando

**Comment by MikhailArkhipov** [comment] 2019-08-15 17:29
@CTrando - most probably `FunctionDefinition.Name` is null or `_function.DeclaringType` is null. Neither guaranteed to exist.

**Comment by cspwizard** [comment] 2019-08-20 13:02
Hi! Can you give an estimate when this issue will be fixed? Have similar issue on MS language server 0.3.47.0 it consumes ~6GB of ram (all available at that moment). The problem was caused by simply opening of https://github.com/marcospereirampj/python-keycloak repo clone

**Comment by MikhailArkhipov** [comment] 2019-08-20 16:15
@cspwizard  - this issue is specifcally about decorators and exception above. Your case may or may not be the same. Please open separate issue. 0.3.59 is now published, restart VSC to update. Thanks.

**Comment by MikhailArkhipov** [comment] 2019-08-21 19:41
Exception is fixed in https://github.com/microsoft/python-language-server/pull/1461

**Closed by MikhailArkhipov** 2019-08-21 19:41 UTC
Labels: bug, feature: analysis
