### ISSUE TITLE
var = var does not trigger Undefined variable linter error

### ISSUE THREAD

**Issue by LucasSubli** [microsoft/python-language-server#1762] opened 2019-11-05 15:31 UTC
## Environment data

- VS Code version: 1.39.2
- Extension version (available under the Extensions sidebar): 2019.10.44104
- OS and version: Ubuntu 18.04

## Expected behaviour

`var = var` when `var` is undefined should trigger `Undefined variable` linter warning
`var = function(var)` does not trigger it either

## Actual behaviour

No linter error is displayed

## Steps to reproduce:
1. add a line in any file and set a new variable equals to itself

**Comment by jakebailey** [comment] 2019-11-06 22:46
Duplicate of #1703.

**Closed by jakebailey** 2019-11-06 22:46 UTC
