### ISSUE TITLE
Intellisense not working with TensorFlow 2.0

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#991] opened 2019-04-18 17:24 UTC
@david-macleod commented on [Wed Apr 17 2019](https://github.com/Microsoft/vscode-python/issues/5350)

## Environment data

- VS Code version: 1.33.1
- Extension version (available under the Extensions sidebar): 2019.3.6558
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.8 Anaconda
- Type of virtual environment used: conda 
- Relevant/affected Python packages and their versions: 
* tensorflow==2.0.0-alpha0
* Microsoft Python Language Server version 0.2.59.0

## Expected behaviour
When I hover over a variable I see the object definition (this is example is using `tensorflow=1.12.0`)

![image](https://user-images.githubusercontent.com/17232877/56324503-ecdd5f00-6166-11e9-893f-6dce3b6d33da.png)

## Actual behaviour

When using `tensorflow==2.0.0-alpha0` I see no object description in the hover overlay
![image](https://user-images.githubusercontent.com/17232877/56324988-75103400-6168-11e9-8caa-57bbb3e5d7a1.png)

## Steps to reproduce:
1. Install tensorflow 
2. Import an object and hover over with cursor

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
************* Module 
2,0,error,no-name-in-module:No name 'keras' in module 'tensorflow'
2,0,error,import-error:Unable to import 'tensorflow.keras.layers'
```

**Comment by jakebailey** [comment] 2019-04-18 17:36
Duplicate of #818.

**Closed by jakebailey** 2019-04-18 17:36 UTC
