### ISSUE TITLE
Code analysis in progress but doesn't start

### ISSUE THREAD

**Issue by rvanlaar** [microsoft/python-language-server#1848] opened 2019-12-20 13:54 UTC
## Environment data

- Language Server version: 0.5.10.0
- OS and version: Ubuntu 19.10
- Python version (& distribution if applicable, e.g. Anaconda): Poetry Python 3.6.9

## Expected behaviour

Jump to definition of code when pressing F12.

## Actual behaviour

Jump to code when that code is 1 step away from my own code, but no further.
Example: 
I can jump to the Django settings on this line:
```from django.conf import settings```

Which jumps me to django/conf/__init__.py: ````settings = LazySettings()```
But I can't jump further to LazySettings

When I have the `__init__.py` open , then close VSCode and reopen VSCode,
then it works as expected. However I can only jump to all things referenced in 
the `__init__.py` and not further.

It works as expected when I have `"python.jediEnabled": true` in my settings.json

## Logs

Log output: https://gist.github.com/rvanlaar/c897c885d5d5a128fc0edefef4e189a8

## Code Snippet / Additional lnformation
![bug-vscode](https://user-images.githubusercontent.com/710771/71259186-1ffc7180-2338-11ea-97ad-f6310ae78f45.gif)

This is the repository and all settings used:
https://github.com/rvanlaar/bug-vscode

**Comment by jakebailey** [comment] 2019-12-20 14:16
Duplicate of #840. This is currently by design; we don't store information for all features in library code.

**Closed by jakebailey** 2019-12-20 14:16 UTC
