### ISSUE TITLE
"python.autoComplete.addBrackets": true not adding brackets

### ISSUE THREAD

**Issue by nadroj-isk** [microsoft/python-language-server#1249] opened 2019-06-23 18:36 UTC
## Environment data

- VS Code version: 1.35.1
- Extension version (available under the Extensions sidebar): XXX
- OS and version: 2019.5.18875
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.2
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info #3977): Language Server

## Expected behaviour

When performing autocompletion for functions brackets should be added for functions automatically.

## Actual behaviour

However using language server it does not. Even with the `"python.autoComplete.addBrackets": true,`

## Steps to reproduce:
1. Create a python file
2. Type `prin`
2. Hit tab or enter to autocomplete to print
3. Brackets are not added even though they should.

When using Jedi, it will autocomplete the brackets, however it will also autocomplete them for import statements and decorators when they should not be used.

**Comment by jakebailey** [comment] 2019-06-24 17:34
Duplicate of #868. Fixed in daily.

**Closed by jakebailey** 2019-06-24 17:34 UTC

**Comment by nadroj-isk** [comment] 2019-06-24 18:44
Which settings am I supposed to use to get this to work?

**Comment by jakebailey** [comment] 2019-06-24 19:04
You should be able to set `"python.autoComplete.addBrackets": true`.

**Comment by nadroj-isk** [comment] 2019-06-25 17:06
I have that however it still doesn’t work with language server. It does with Jedi

**Comment by jakebailey** [comment] 2019-06-25 17:07
Please provide a code sample that we can test; also ensure that you are running the latest language server build (currently 0.3.20).

**Comment by nadroj-isk** [comment] 2019-06-27 00:17
```json
{
    "workbench.colorTheme": "Solarized Dark",
    // Command Prompt
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
    "workbench.iconTheme": "material-icon-theme",
    "code-runner.runInTerminal": true,
    "explorer.confirmDelete": false,
    "window.zoomLevel": 0,
    "breadcrumbs.enabled": false,
    "python.formatting.provider": "autopep8",
    "editor.formatOnSave": true,
    "python.formatting.autopep8Args": [
        "--ignore",
        "E402",
        "--max-line-length=200"
    ],
    "git.autofetch": true,
    "explorer.confirmDragAndDrop": false,
    "python.autoComplete.addBrackets": true,
    "code-runner.clearPreviousOutput": true,
    "code-runner.ignoreSelection": true,
    "code-runner.preserveFocus": false,
    "code-runner.saveFileBeforeRun": true,
    "extensions.ignoreRecommendations": false,
    "code-runner.respectShebang": false,
    "code-runner.executorMap": {
        "python": "$pythonPath $fullFileName"
    },
    "C_Cpp.updateChannel": "Insiders",
}
```

Here is my settings.json file. How do I see which version of language server  I am on?

**Comment by jakebailey** [comment] 2019-06-27 00:20
Check your output panel. See: https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#filing-an-issue

Note that your settings files doesn't indicate that you have enabled the langauge server at all; you're missing jediEnabled=false.

**Comment by nadroj-isk** [comment] 2019-06-27 00:25
It's there now, and I've reloaded VS Code. It is still adding the brackets to the imports. Also I followed the steps below but it did not print anything out, I was just in a terminal. 

> CTRL + Shift + P >> Python: Create Terminal >> Select "Output" >> Select "Python" from the dropdown menu in the top right of the output window). Look for the line Microsoft Python Language Server version X in the console.

**Comment by jakebailey** [comment] 2019-06-27 05:56
Go to the top bar, View > Output, and then flip it to Python on the dropdown on the right.

(Those instructions are definitely a long way of doing that, which I should fix.)

**Comment by nadroj-isk** [comment] 2019-06-27 13:17
Microsoft Python Language Server version 0.3.20.0 is the version I have

**Comment by jakebailey** [comment] 2019-06-27 16:10
Okay, but we'll still need some code example where the brackets aren't added when that option is enabled to see what is going on.

**Comment by nadroj-isk** [comment] 2019-06-27 23:20
Start a new python file
Type `from time import tim` 
Hit enter to accept "time" suggestion and for me it autocorrects to from time import time()

**Comment by jakebailey** [comment] 2019-06-27 23:25
I can reproduce it, yeah. That was #573, and #1241 probably reopened it.

**Comment by jakebailey** [comment] 2019-06-27 23:26
I'm just going to reopen #573. Thanks for the example.

**Comment by nadroj-isk** [comment] 2019-06-27 23:28
No problem thanks for being so active!
