### ISSUE TITLE
Mark not used modules in Python in VS Code as like in PyCharm

### ISSUE THREAD

**Issue by hd016** [microsoft/python-language-server#1887] opened 2020-01-26 13:05 UTC
Pycharm is identifiying not used modules in the Pyhton script, so you can have an overview about the modules. In my Template the unused modules are grey, the used modules are blue. I googled it, but I didnt found an extension to resolve this in VS Code.

**Comment by jakebailey** [comment] 2020-01-27 21:21
Duplicate of #18.

**Closed by jakebailey** 2020-01-27 21:21 UTC
