### ISSUE TITLE
Intellisense doesn't seem to work for pandas

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#575] opened 2019-02-01 23:40 UTC
@rchiodo commented on [Fri Feb 01 2019](https://github.com/Microsoft/vscode-python/issues/4253)

## Environment data

- VS Code version: 1.30.1
- Extension version (available under the Extensions sidebar): 2019.1.0
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.6
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Relevant/affected Python packages and their versions: xxx

## Expected behaviour

Intellisense works. 

## Actual behaviour

![bug.gif](https://images.zenhubusercontent.com/5bda265b648e32720db70349/b6dbf2ae-e6b1-4d8b-86f3-d05ddcc30aa3)

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
Microsoft Python Language Server version 0.1.78.0
Initializing for C:\Users\rchiodo\AppData\Local\Continuum\anaconda3\python.exe
##########Linting Output - pylint##########
************* Module training
27,0,error,undefined-variable:Undefined variable 'os'

-------------------------------------------------------------------

Your code has been rated at 7.22/10 (previous run: 10.00/10, -2.78)



##########Linting Output - pylint##########
************* Module training
26,0,error,syntax-error:invalid syntax (<unknown>, line 26)

```

**Comment by jakebailey** [comment] 2019-02-01 23:41
Duplicate of #358.

**Closed by jakebailey** 2019-02-01 23:41 UTC
