### ISSUE TITLE
Diagnostics not being cleared after document change

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#386] opened 2018-11-12 17:50 UTC
_From @darrickyee on November 9, 2018 15:30_

## Environment data

- VS Code version: 1.28.2
- Extension version (available under the Extensions sidebar): 2018.10.0
- OS and version: Windows 7
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.0 (base)
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A

## Actual behavior

While typing a name, the Problems window raises "used before definition" warnings that do not go away when the name is completed.

![error](https://user-images.githubusercontent.com/18172544/48270524-50b96a00-e408-11e8-93f3-b3642d396efe.jpg)

The following actions do NOT fix this:

- Closing and reopening the file
- Modifying the name to something else and back again
- Deleting the name or entire line
- Deleting all content in the file and re-pasting

The only reliable way I have found so far to fix this is to restart VSCode.

Unlike https://github.com/Microsoft/vscode-python/issues/2290, this does NOT happen when jedi is enabled.  This also does not appear to be a linter issue, as the (pylint) output does not show any of these warnings:

![pylint](https://user-images.githubusercontent.com/18172544/48270799-e523cc80-e408-11e8-8506-2384eea7763b.jpg)

Can't seem to reproduce this with a toy example, but it is happening often enough in real projects that it is becoming a major usability issue.  The number of "problems" explodes with phantom entries and makes the tool useless.

## Expected  behavior

Don't show problems in Problems window if they don't exist.

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
Starting Microsoft Python language server.
Microsoft Python Language Server version 0.1.60.0
Initializing for C:\Python37\python.exe
##########Linting Output - pylint##########
************* Module xml2data.elem.generic
40,4,convention,C0103:Attribute name "c" doesn't conform to snake_case naming style

------------------------------------------------------------------

Your code has been rated at 9.76/10 (previous run: 9.76/10, +0.00)

```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`)

[console.log](https://github.com/Microsoft/vscode-python/files/2566408/console.log)

_Copied from original issue: Microsoft/vscode-python#3277_

**Comment by jakebailey** [comment] 2018-11-14 21:51
If you want to silence this message (until it's fixed), you can add this to your settings.json file:

```json
"python.anaysis.disabled": [
    "use-before-def"
]
```

**Comment by jakebailey** [comment] 2018-11-15 17:14
I had a typo in that snippet, should have said "analysis" spelled correctly. Oops.

**Comment by bpartridge** [comment] 2018-12-13 06:12
With https://github.com/Microsoft/vscode-python/issues/3514 causing Jedi to effectively fork-bomb our systems, and this issue preventing us from turning off Jedi, we're stuck between a rock and a hard place. Is the core team able to reproduce?

**Comment by jakebailey** [comment] 2018-12-13 07:54
I tried for a few weeks to reproduce this and #391, without avail. If you have some reproducing case that's publicly available, I'd love to have it.

Otherwise, you can disable all of the warnings the language server produces in your settings.json:

```json
"python.analysis.disabled": [
	"use-before-def",
	"unresolved-import"
]
```

And continue to use pylint/flake8/pep8 (which the extension continues to support).

With the ongoing analysis simplification, all of the code which produces these diagnostics will be removed and rewritten completely, so I would expect to see this sort of issue go away as well.

**Comment by jakebailey** [comment] 2018-12-13 07:57
Also be aware of Brett's comment (https://github.com/Microsoft/vscode-python/issues/3514#issuecomment-444686905) which states that the Jedi version may simply be rolled back for the upcoming release, but I'm not personally involved in that sort of thing.

**Comment by lachlan-eagling** [comment] 2018-12-19 05:57
Also having this issue, I was able to reproduce it as per my comment on the original issue https://github.com/Microsoft/vscode-python/issues/3277#issuecomment-448478448

**Comment by happycoder97** [comment] 2019-02-04 13:22
Also having this issue. It happens in rust too

**Comment by happycoder97** [comment] 2019-02-04 13:49
C++ Screenshot:
![whatsapp image 2019-02-04 at 7 18 23 pm](https://user-images.githubusercontent.com/40014472/52212093-b3a88900-28b1-11e9-8498-429f3752b0bf.jpeg)

**Comment by simkimsia** [comment] 2019-02-26 07:02
The fix helped in [#386 (comment)](https://github.com/Microsoft/python-language-server/issues/386#issuecomment-438831864)

Thank you 🙏 

Do I need to remove the ignore when this issue is fixed be it in the LS or in vscode itself?

**Comment by jakebailey** [comment] 2019-02-26 07:36
Yes, if you'd like to see the message show up. We plan to reimplement this specific message (`use-before-def`) for the new LS, but other items have taken priority.

**Comment by simkimsia** [comment] 2019-02-26 09:25
Thanks 🙏 No hurry on this. I didn't miss it that much previously. 

Since I've now subscribed to the issue, I'll do so when this is solved. Really thank you for closing my original issue with this fix.

**Comment by MikhailArkhipov** [comment] 2019-03-16 05:19
Should be gone in 0.2

**Closed by MikhailArkhipov** 2019-03-16 05:19 UTC
