### ISSUE TITLE
Undefined variable 'super' in Python language server

### ISSUE THREAD

**Issue by PetterS** [microsoft/python-language-server#1817] opened 2019-11-27 08:54 UTC
Issue Type: <b>Bug</b>

Python language server does not recognize the "super" built-in for initializing a base class.

![image](https://user-images.githubusercontent.com/772305/69708379-cec3de00-10fb-11ea-85f4-9bd027b97078.png)

Extension version: 2019.11.50794
VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (2.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jakebailey** [comment] 2019-11-27 22:07
This is probably a duplicate of #1697. I'd try out the beta. https://github.com/microsoft/python-language-server/wiki/Versioning-and-download-channels

**Comment by PetterS** [comment] 2019-11-28 08:01
Sounds likely. It only went away when I restarted the editor.

**Closed** 2019-12-02 17:24 UTC
