### ISSUE TITLE
False positive in lambda in list comprehension

### ISSUE THREAD

**Issue by TomSputz** [Microsoft/python-language-server#912] opened 2019-04-09 18:58 UTC
```py
print(lambda: x for x in ())
```
Raises `Undefined variable: 'x'` at the first `x`

**Comment by jakebailey** [comment] 2019-04-09 19:10
This should be a duplicate of #830. The PR that fixed it has not yet been released to the stable channel (a bit more testing to do), but there should be a build in the daily download channel within an hour if you'd like to try it and see if it fixes your issue. I'll reply when the build completes.

Closing for now.

**Closed by jakebailey** 2019-04-09 19:10 UTC

**Comment by jakebailey** [comment] 2019-04-09 19:33
The build is in the daily channel, which you can enable by setting:

```json
"python.analysis.downloadChannel": "daily"
```

Note that this code may be buggy. To switch back to stable, remove the setting and remove the languageServer folder in the VS Code extension directory. (Microsoft/vscode-python#3977)
