### ISSUE TITLE
Do not show auto-completions for ellipsis.

### ISSUE THREAD

**Issue by ericsnowcurrently** [microsoft/python-language-server#1397] opened 2019-07-15 22:45 UTC
In Python `...` is syntactic sugar for `Ellipsis`.  However, whenever I type `...` VSCode pops up a completions window.  That is super annoying.

FWIW, the behavior is pretty much the same with both Jedi and the language server, though the actual offered completions are different.

**Comment by jakebailey** [comment] 2019-07-31 21:53
What behavior are you looking for more than the current behavior?

![issue1397](https://user-images.githubusercontent.com/5341706/62250875-f8b20180-b3a2-11e9-9971-ee4f2e412e71.gif)

We used to show unwanted completion until #1344 was merged. Now we only show it after `....`, but `...` is a value, and I can do this in the REPL:

```
>>> ...
Ellipsis
>>> ....__name__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ellipsis' object has no attribute '__name__'
```

**Comment by jakebailey** [comment] 2019-07-31 21:54
Oh, this is transferred from 16 days ago, and #1344 wouldn't have been out then. Closing as a duplicate of #927, then.

**Closed by jakebailey** 2019-07-31 21:54 UTC
