### ISSUE TITLE
Get autocomplete and function overrides for python

### ISSUE THREAD

**Issue by b99andla** [microsoft/python-language-server#1981] opened 2020-04-01 09:06 UTC
In IntelliJ we have a function which lets us get autcomplete and assistance for adding an inherited function.

Is there any way to recreate this behaviour in VS Code with the build in Python interpreter?

**It lets us override specific functions by using ctrl+O**
![Screenshot 2020-03-20 at 12 06 15](https://user-images.githubusercontent.com/8145201/78119463-c4e31c00-7408-11ea-83f5-eed6d4acf7c3.png)

**It lets us see which methods in the current class is overridden.**
![Screenshot 2020-03-20 at 12 06 28](https://user-images.githubusercontent.com/8145201/78119470-c7de0c80-7408-11ea-83cc-3374b084fa2f.png)

**Comment by jakebailey** [comment] 2020-04-01 20:15
Duplicate of #1641.

**Closed by jakebailey** 2020-04-01 20:15 UTC
