### ISSUE TITLE
Automatically detect user module in the same subfolder of the current script

### ISSUE THREAD

**Issue by fireattack** [microsoft/python-language-server#1822] opened 2019-12-02 23:37 UTC
Currently LS only searches the root for the user module unless you manually add paths to `python.autoComplete.extraPaths`.

But when editing a file, say, `sub/script.py` with content like
```python
from module import myfunc
```
LS should automatically search for modules in folder `sub/` (`sub/module.py` in this case) without manual setting, because Python will always search modules in the directory containing the input script.

Currently it will throw an "unresolved import" warning despite the script can run just fine.

**Comment by jakebailey** [comment] 2019-12-02 23:39
Duplicate of #1602.

**Closed by jakebailey** 2019-12-02 23:39 UTC
Labels: enhancement
