### ISSUE TITLE
missing completions 

### ISSUE THREAD

**Issue by kirk86** [microsoft/python-language-server#1694] opened 2019-10-15 12:13 UTC
## Environment data

- Language Server version: 0.2
- OS and version: OSx
- Python version (Anaconda): 3.6

## Expected behaviour and Actual behaviour
Please have a look [here](https://github.com/emacs-lsp/lsp-python-ms/issues/64#issuecomment-542179111)

**Comment by jakebailey** [comment] 2019-10-15 16:07
This is very likely #1414.

Since you did not fill out our template, I don't know if you have caching enabled. Try disabling it with:

```
"python.analysis.cachingLevel": "None"
```

But please fill out the requested info in the future (mirrored here: https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#filing-an-issue).

**Comment by kirk86** [comment] 2019-10-15 19:55
Thanks, I wasn't sure how to get info to start with since I wasn't using VSCode but emacs, but I'll look into it and try to provide back any missing info.

**Comment by ernestom** [comment] 2019-10-16 07:52
@kirk86 I had the same problem and disabling the cache did the trick.

**Comment by kirk86** [comment] 2019-10-16 08:41
@ernestom Thanks, I'll give it a shot.

**Comment by jakebailey** [comment] 2019-10-16 16:29
Note that disabling caching is probably just a workaround for #1414, which has the implication of incomplete module information being stored to disk (then reloaded later).

**Comment by jakebailey** [comment] 2019-10-17 16:51
Closing as a duplicate of #1414 for now.

**Closed by jakebailey** 2019-10-17 16:51 UTC
