### ISSUE TITLE
Automatically closing brackets not supported

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/python-language-server#112] opened 2018-09-19 23:40 UTC
Microsoft/vscode-python#1772

Don said this was something that required language server support.

**Comment by MikhailArkhipov** [comment] 2018-09-24 21:03
This is actually not about auto-closing brackets. Auto-close is when user types `(`, editor adds `)`. This is VS Code internal thing, we do not control it - same for quotes. #1772 is about auto-inserting `()` on completion of function names. I.e. `print` completes to `print()` with caret inside `(|)`.

**Comment by MikhailArkhipov** [comment] 2018-09-26 01:10
Dupe of #35

**Closed** 2018-09-26 01:11 UTC
