### ISSUE TITLE
the use-before-definition is broken

### ISSUE THREAD

**Issue by simkimsia** [Microsoft/python-language-server#658] opened 2019-02-25 22:53 UTC
I recently upgraded the Python because it was prompted by vscode

Now I keep getting weird warnings non-stop that refuse to go away

Version 1.31.1 (1.31.1)

<img width="652" alt="screenshot 2019-02-26 at 6 51 46 am" src="https://user-images.githubusercontent.com/245021/53374395-22e63a00-3993-11e9-98e3-e969b0a558ec.png">
<img width="649" alt="screenshot 2019-02-26 at 6 52 05 am" src="https://user-images.githubusercontent.com/245021/53374396-237ed080-3993-11e9-8d87-3a5ade190c3c.png">

**Comment by jakebailey** [comment] 2019-02-25 22:58
Closing as a duplicate of #386, #626.

See https://github.com/Microsoft/python-language-server/issues/386#issuecomment-438831864 to disable the message.

The new LS in `master` reimplements diagnostics so I don't believe they will have this issue, but we haven't yet reimplemented `use-before-def`.

**Closed by jakebailey** 2019-02-25 22:58 UTC

**Comment by simkimsia** [comment] 2019-02-26 06:41
Oh thank you @jakebailey 

the fix helped. 

I will comment further in [#386 (comment)](https://github.com/Microsoft/python-language-server/issues/386#issuecomment-438831864)
