### ISSUE TITLE
unresolved import where there should be none

### ISSUE THREAD

**Issue by 5hunx** [microsoft/python-language-server#2008] opened 2020-04-25 22:23 UTC
## Environment data

- Language Server version: 0.5.45.0 
- OS and version: 10 Pro 1903
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.2

## Expected behaviour

win32api imports and no error occurres

## Actual behaviour

win32api imports (and works) but i get the yellow error : Python(unresolved-import)
https://imgur.com/Z49YI0q

## Code Snippet / Additional lnformation

Heres an example code where the error occurres.

```python
import win32api
from math import floor

def uptime():
    msec = win32api.GetTickCount()
    sec = msec/1000.0
    tmin = sec/60.0
    hours = tmin/60.0
    days = hours/24.0
    
    if floor(days) == 1:
        print(floor(days))
        up_var =str(floor(days)) + " days " + str(floor(hours) % 24) + " hours " + str(floor(tmin) % 60) + " mins " + str(floor(sec) % 60) + " secs"
    elif floor(hours) >= 1:
        up_var =str(floor(hours)) + " hours " + str(floor(tmin) % 60) + " mins " + str(floor(sec) % 60) + " secs"
    elif floor(tmin) >= 1:
        up_var =str(floor(tmin)) + " mins " + str(floor(sec) % 60) + " secs"
    else:
        up_var =str(floor(sec)) + " secs"
    return(up_var)

print(uptime())
```

This code works for me
Sorry for my bad english.

**Comment by jakebailey** [comment] 2020-04-25 22:37
Duplicate of #1360.

**Closed by jakebailey** 2020-04-25 22:37 UTC
