### ISSUE TITLE
Function documentation colored red when a parameter name contains an underscore

### ISSUE THREAD

**Issue by epetrovski** [microsoft/python-language-server#2087] opened 2020-06-24 18:59 UTC
## Environment data

-   VS Code version: 1.46.1
-   Extension version: 2020.6.89148
-   OS and version: MacOS 10.15.5 (but same on Windows 10)
-   Python version: 3.7.7
-   Type of virtual environment used: None
-   Value of the `python.languageServer` setting: Microsoft

## Expected behaviour

Display function documentation normally when the name of a parameter contains an underscore.

## Actual behaviour

Displays the name of a parameter containing an underscore and following text colored red:

<img width="712" alt="screen" src="https://user-images.githubusercontent.com/24638276/85615208-2e677500-b65c-11ea-9ced-106244beef30.png">

## Steps to reproduce:

Write a function where one of the parameter names contains an underscore and document that parameter in a docstring.

```python
def foo(param, a_param):
    """
    This is a function.

    Parameters
    ----------
        param (int): A parameter.
        a_param (int): And another.
    """
    pass
```

**Comment by jakebailey** [comment] 2020-06-24 20:24
Duplicate of #613, which covers this extra syntax that is neither markdown or ReST. That block is indented and is getting loosely translated into a code block (since indention in markdown means a code block).

**Closed by jakebailey** 2020-06-24 20:24 UTC

**Comment by epetrovski** [comment] 2020-06-25 06:38
Sorry for the duplicate, was difficult to search for.
