### ISSUE TITLE
time.strptime (and others) info not being pulled from typeshed

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#300] opened 2018-10-22 22:47 UTC
`time` is in typeshed, where `strptime` is given the hint:

```python
def strptime(string: str, format: str = ...) -> struct_time: ...
```

But the following `pyi` text is showing up in the `languageServer` folder instead:

```python
def strptime(string, format):
    "strptime(string, format) -> struct_time\n\nParse a string ..." # truncated
    return ''
```

Meaning that all completion on its return value is `str`.

There are other functions which make use of `struct_time`, like:

```python
def localtime(secs: Optional[float] = ...) -> struct_time: ...
```

Which shows up in `languageServer` as:

```python
def localtime():
    "localtime([seconds]) -> (tm_year,tm_mon,tm_mday,tm_hour,tm_min,\n                          tm_sec,tm_wday,tm_yday,tm_isdst)\n\nConvert seconds since ..." # truncated
    return tuple()
```

Which is _sort of_ correct, since `struct_time` is a `NamedTuple`, but offers no completions, whereas the actual `struct_time` in the same `pyi` file actually contains the right information about its properties.

**Comment by MikhailArkhipov** [comment] 2018-10-24 17:57
https://github.com/Microsoft/python-language-server/issues/15

**Comment by MikhailArkhipov** [comment] 2018-10-30 17:42
So what's wrong with 

![image](https://user-images.githubusercontent.com/12820357/47738380-3fb27100-dc30-11e8-9629-dbfd59c40798.png)

![image](https://user-images.githubusercontent.com/12820357/47738426-5b1d7c00-dc30-11e8-8ff6-c4f5df64df50.png)

![image](https://user-images.githubusercontent.com/12820357/47738473-6ec8e280-dc30-11e8-9dc4-c632550253d4.png)

If the case is about named tuple, then it is dupe of #15. Otherwise signatures and return types appear correct.

**Comment by jakebailey** [comment] 2018-10-30 18:03
![image](https://user-images.githubusercontent.com/5341706/47739398-84d7a280-dc32-11e8-939f-49b1bbd53841.png)

Even with #321. It claims to return `struct_time` in the hover, but almost everything is `str`, except for `__new__` which says it's from `struct_time`.

Now, if you assign its result, and hover:

![image](https://user-images.githubusercontent.com/5341706/47739550-d7b15a00-dc32-11e8-8f8e-4567b7dccf4f.png)

The part where you can't complete `struct_time`'s members is probably #15, but the fact that the analyzer is claiming it's returning a string is not.

In no path should strptime return a `str`, and the typeshed for the `time` module says `struct_time`. I might be wrong about this, as I haven't yet explored that part of the code, but I think the fact that a `pyi` file shows up in `languageServer` means that it's the scraper that's doing this.

**Comment by MikhailArkhipov** [comment] 2019-01-30 05:20
New LS does

![image](https://user-images.githubusercontent.com/12820357/51959951-a13ed300-240b-11e9-9ced-f12122a4fef6.png)

**Comment by MikhailArkhipov** [comment] 2019-02-06 16:29
https://github.com/Microsoft/python-language-server/pull/546

**Closed by MikhailArkhipov** 2019-02-06 16:29 UTC
Labels: GA
