### ISSUE TITLE
Microsoft.Python.LanguageServer using excessive ram and high CPU usage

### ISSUE THREAD

**Issue by Pranay144** [Microsoft/python-language-server#610] opened 2019-02-14 09:16 UTC
![captures](https://user-images.githubusercontent.com/45161803/52776258-3c1fea00-3067-11e9-83de-3c8c3352f65f.PNG)

**Comment by MikhailArkhipov** [comment] 2019-02-14 15:47
The issue is fixed in the upcoming major redesign which will be available in the beta channel first in the upcoming weeks. Stay tuned. The change cannot be ported back sorry since the code base is completely different.

**Comment by MikhailArkhipov** [comment] 2019-02-14 16:10
#568 for tracking

**Closed by MikhailArkhipov** 2019-02-14 16:10 UTC
Labels: duplicate

**Comment by MikhailArkhipov** [comment] 2019-03-06 22:38
0.2.16 is now available on beta channel. 
```json
"python.analysis.downloadChannel": "beta"
```

**Comment by Astlaan** [comment] 2019-03-07 21:40
Got that too.
Issue Type: <b>Performance Issue</b>

![image](https://user-images.githubusercontent.com/10374970/53990734-39c22480-4129-11e9-92b2-275d40de82f4.png)
I tried reopening VScode, but the Language server started hogging resources again.
I'm pasting the rundata returned from VS Code below.

Extension version: 2019.2.5558
VS Code version: Code 1.32.0 (507312a3e3b34b084b467dfd983263bc7c9d87e0, 2019-03-06T18:57:55.589Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (1.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    92	   220	code main
    2	   578	  1224	   gpu-process
    3	    66	  1608	   window (Issue Reporter)
    0	    63	  3112	   shared-process
    0	   182	  9752	   window (Release Notes: 1.32.0 - Code - Visual Studio Code)
    0	    10	  6252	     watcherService 
    0	     8	  9332	       console-window-host (Windows internal process)
    0	   116	  9556	     extensionHost
    0	    31	  7680	       "C:\Users\Diogo\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Diogo\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=9556
   33	  2215	 11788	       C:\Users\Diogo\.vscode\extensions\ms-python.python-2019.2.5558\languageServer.0.1.80\Microsoft.Python.LanguageServer.exe
    0	     8	  2440	         console-window-host (Windows internal process)
    0	    11	 14188	     electron-crash-reporter
    0	   377	 11684	   window (undefined)
```

</details>

**Comment by jakebailey** [comment] 2019-03-07 21:45
See Mikhail's message above. There is a new version you should test which does not exhibit this behavior. You can see which version of the language server you're running in the Python output panel.
