### ISSUE TITLE
Some hover tooltips have a trailing two spaces

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#444] opened 2018-12-03 18:18 UTC
![image](https://user-images.githubusercontent.com/5341706/49392781-4f681e00-f6e4-11e8-97e5-0731deca3ad5.png)

![image](https://user-images.githubusercontent.com/5341706/49392817-660e7500-f6e4-11e8-8fbe-a264d8db3a1e.png)

Which aren't visual glitches, as I can highlight the text with my mouse (as above). It only happens for these simple one-liners. More complicated tooltips from docstrings don't seem to have this issue, likely because the text in these two examples is triple-quoted for syntax highlighting, while docstrings are not.

**Comment by MikhailArkhipov** [comment] 2018-12-04 05:51
By design.
```cs
            foreach(var s in _md) {
                sb.AppendLine(s + "  "); // Keep hard line breaks
            }
```

**Comment by jakebailey** [comment] 2018-12-04 06:49
If we know that the text is a single line, then it might be good to just not add the double space.

Past that, I think it's a little strange that we're controlling the line breaks ourselves rather than letting the renderer do it, but that's a different discussion.

**Comment by MikhailArkhipov** [comment] 2018-12-05 04:46
Because we want text to appear exactly as it is formatted inside the Python file. Many docs include manually formatted tables and code blocks which are getting messed up if line breaks are not preserved.

**Comment by MikhailArkhipov** [comment] 2018-12-19 23:11
Since this is not a bug, closing. @424 is for general improvements.

**Closed by MikhailArkhipov** 2018-12-19 23:11 UTC
Labels: bug, feature: tooltips
