### ISSUE TITLE
Autocompletion issues with Selenium

### ISSUE THREAD

**Issue by illogikus** [microsoft/python-language-server#1952] opened 2020-03-18 15:43 UTC
Hello,
I have an issue with autocompletion with selenium.
It works in PyCharm, but not in VSCode, so I suspect there is something that could be improved there. (or maybe I am missing something on my side?)

## Environment data

- VS Code version: 1.43.0
- Extension version (available under the Extensions sidebar): 2020.2.64397
- OS and version: Ubuntu 18.04.4 LTS
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.9
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
- Relevant/affected Python packages and their versions: selenium==3.141.0 
- Relevant/affected Python-related VS Code extensions and their versions: no other extension installed
- Jedi or Language Server?: I seem to have the issue with both
- Value of the `python.languageServer` setting: Microsoft

## Expected behaviour

I expected to have some auto-completion hints (like I have in PyCharm)

## Actual behaviour

No hints at all

## Steps to reproduce:
On Ubuntu 18.04:
In a terminal:
```
virtualenv -p python3 /path/to/venv/myvenv
. /path/to/venv/myvenv/bin/activate
pip install selenium
```

Set "python.venvPath" to '/path/to/venv' to the venv path
Set the python interpreter to the one defined above.
Then open a toto.py file and try this code snippet:
```
from selenium import webdriver
browser = webdriver.Chrome()
elem = browser.find_element_by_id('toto')
elem.
```
You will see that the autocompletion works fine on `browser.`:

![image](https://user-images.githubusercontent.com/17251853/76978310-d3c0cd80-6936-11ea-934c-cd02f7ba3bd5.png)

 but not on `elem.`:

![image](https://user-images.githubusercontent.com/17251853/76978358-dfac8f80-6936-11ea-9c33-e780ce0c5a18.png)

It works in PyCharm though:
![image](https://user-images.githubusercontent.com/17251853/76978453-fbb03100-6936-11ea-82a3-ee83aa27ca1d.png)

Is there something I am missing here?
Is the issue only on my side, or can you guys reproduce it as well?

**Comment by jakebailey** [comment] 2020-03-18 20:41
Duplicate of #785.

**Closed by jakebailey** 2020-03-18 20:41 UTC

**Comment by illogikus** [comment] 2020-03-19 07:54
Thanks @jakebailey ,
Sorry for the duplicate.
