### ISSUE TITLE
Variable substitution doesn't work in settings.json file

### ISSUE THREAD

**Issue by awav** [microsoft/python-language-server#1812] opened 2019-11-25 10:47 UTC
Hello everyone,

Here is logs for language server:

```bash
[Info  - 3:42:34 PM] User search paths:
[Info  - 3:42:34 PM]     /Users/artemav/code/GPflow/${env:HOME}/.local/virtual-site-packages
[Info  - 3:42:36 PM] done.
[Info  - 3:42:36 PM] Analysis restarted
```

Here are settings:
```json
    "python.autoComplete.extraPaths": [
        "/Users/artemav/.local/virtual-site-packages",
        "${env:HOME}/.local/virtual-site-packages"
    ]
```

And not only `env` variables don't work, `workspaceFolder` variable doesn't work either. Check this thread https://github.com/microsoft/vscode-python/issues/7684#issuecomment-557730292.

**OS: macOS Mojave 10.14.6
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0**

**Comment by jakebailey** [comment] 2019-11-25 21:39
Duplicate of #1783.

**Closed by jakebailey** 2019-11-25 21:39 UTC
