### ISSUE TITLE
Type annotations for 'for' loop variables not recognized

### ISSUE THREAD

**Issue by malmaud** [microsoft/python-language-server#1528] opened 2019-09-09 16:40 UTC
There's no LS suggestions for `x` here (on the nightly download channel):

```python
def f(xs: List):
    for x in xs:  # type: str        
        x.
```

This is the correct syntax for introducing a type annotation on variables introduced in `for` loops and is utilized by mypy and PyCharm.

**Comment by jakebailey** [comment] 2019-09-09 16:42
Duplicate of #1026.

**Closed by jakebailey** 2019-09-09 16:42 UTC
Labels: enhancement

**Comment by malmaud** [comment] 2019-09-09 16:44
Oops, sorry.
