### ISSUE TITLE
Horrible experience with Python Language Server

### ISSUE THREAD

**Issue by awav** [microsoft/python-language-server#1813] opened 2019-11-25 11:00 UTC
Hello everyone,

Lately, python language server is **super** laggy  and buggy (+ https://github.com/microsoft/vscode-python/issues/8768)

1. Often Language Server emits errors like below and my guess it depends on "weather conditions" - absolutely unpredictable.

```
Unable to open 'python.pyi': Unable to read file (Error: File not found (/Users/artemav/Library/Caches/Microsoft/Python Language Server/stubs.v4/fJB3UsE4Gq6YclHi4GoLw6ngBkMtdMTdkOlmPhNG7K8=/python.pyi)).
```

2. I cannot get any reasonable autocompletion, even for standard python things! Sometimes, I see this error in "Developer Tools".

```
ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
```

3. At workspace some folders are indexed and others are not, but have similar code and use same dependencies...

**PS: I have to switch to Pycharm! I'm ready to help with debugging the issue and I'm sorry not providing MWE how to reproduce it, because all logs are nearly empty:**

```
[Info  - 9:23:53 PM] Analysis cache path: /Users/artemav/Library/Caches/Microsoft/Python Language Server
[Info  - 9:23:53 PM] Microsoft Python Language Server version 0.4.114.0
[Info  - 9:23:53 PM] Workspace root: /Users/artemav/code/bayesian-optimization
[Info  - 9:23:53 PM] GetCurrentSearchPaths /Users/artemav/anaconda3/envs/tf/bin/python 
[Info  - 9:23:53 PM] Interpreter search paths:
[Info  - 9:23:53 PM]     /Users/artemav/anaconda3/envs/tf/lib/python3.7
[Info  - 9:23:53 PM]     /Users/artemav/anaconda3/envs/tf/lib/python3.7/lib-dynload
[Info  - 9:23:53 PM]     /Users/artemav/.local/virtual-site-packages
[Info  - 9:23:53 PM]     /Users/artemav/anaconda3/envs/tf/lib/python3.7/site-packages
[Info  - 9:23:53 PM]     /Users/artemav/code/grand_prix
[Info  - 9:23:53 PM]     /Users/artemav/code/GPflow
[Info  - 9:23:53 PM] User search paths:
[Info  - 9:23:56 PM] Initializing for /Users/artemav/anaconda3/envs/tf/bin/python
[Info  - 9:23:58 PM] Analysis caching mode: None.
```

**OS: macOS Mojave 10.14.6
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0**

**Comment by jakebailey** [comment] 2019-11-27 22:15
1 is a bug.

2 is two unrelated things. We'd like to know what autocomplete is not showing up that should. The language server cannot print to that debug window (that's VS Code).

3 I'm not sure what you mean by "indexed". Specifically autocompletion? Linting? Workspace symbol indexing?

We need something specific to work on here. Do you have the code that causes issues?

**Comment by awav** [comment] 2019-11-28 18:32
> I cannot get any reasonable autocompletion, even for standard python things! Sometimes, I see this error in "Developer Tools".

My guess, I'm experiencing the same issue as here: https://github.com/microsoft/python-language-server/issues/1806. The analyzing hangs and, in the end, the autocompletion stops working.

> 3 I'm not sure what you mean by "indexed". Specifically autocompletion? Linting? Workspace symbol indexing?

I mean that in a workspace with three TensorFlow based projects, - "Jumping to Definition" and all other features related to the Python Language Server **does** work for only one folder out of three.

**Comment by awav** [comment] 2019-12-04 13:39
@jakebailey, any update?

**Comment by jakebailey** [comment] 2019-12-04 18:03
No, I would reply if there were. May I assume that by multiple projects in a workspace, you mean VS Code's multi-root workspace system and not just three folders in a single place?

**Comment by awav** [comment] 2019-12-04 21:58
> May I assume that by multiple projects in a workspace, you mean VS Code's multi-root workspace system and not just three folders in a single place?

That's right. I have three folders in one workspace. If I open projects individually, the autocomplete works.

**Comment by MikhailArkhipov** [comment] 2019-12-16 18:12
- (1) is fixed by https://github.com/microsoft/python-language-server/pull/1831, currently in beta channel, 0.5.8+.
- (2) is about the fact that LS is per project and multi-root workspace means extension runs multiple LS processes. LS processes are isolated and do not share information. This is currently by design. Amount of work is non-trivial. Basically, issues #1196 and #1195. 

I am going to dupe against #1196.

**Closed** 2019-12-16 18:12 UTC
Labels: duplicate

**Comment by klajddd** [comment] 2021-01-01 15:06
I am having the same issue:

I have a blank python file with these 2 lines:

a='llklk'

a.lower()

when trying to access the documentation of lower(), this error appears:

Unable to open 'python3.pyi': Unable to read file '/Users/MYUSERNAME/Library/Caches/Microsoft/Python Language Server/stubs.v4/5Gj0QnRdrb5AHReKMGD6k6EdoYIw-qZ4xCPncKJOn_k=/python3.pyi' (Error: Unable to resolve non-existing file '/Users/MYUSERNAME/Library/Caches/Microsoft/Python Language Server/stubs.v4/5Gj0QnRdrb5AHReKMGD6k6EdoYIw-qZ4xCPncKJOn_k=/python3.pyi').
