### ISSUE TITLE
Unable to find document with dash in filename

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/python-language-server#774] opened 2019-03-18 17:05 UTC
channel beta
STR:
* create file:///home/yan/dev/Untitled-1.py
* open it
* Unable to find document file:///home/yan/dev/Untitled-1.py

**Comment by jakebailey** [comment] 2019-03-18 17:07
Duplicate of #736.

**Closed by jakebailey** 2019-03-18 17:07 UTC
