### ISSUE TITLE
cannot find Pattern in typing

### ISSUE THREAD

**Issue by chen19901225** [microsoft/python-language-server#1225] opened 2019-06-19 02:35 UTC
## Environment data

- VS Code version: 1.35.1
- Extension version (available under the Extensions sidebar): python 2019.5.18875
- OS and version: win10
- Python version (& distribution if applicable, e.g. Anaconda): python3.7.3 32-bit
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...):  N/A
- Relevant/affected Python packages and their versions: XXX
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info #3977):  Language Server

## Expected behaviour

`a.` suggest field or method

## Actual behaviour
```
import typing
import re
a: typing.Pattern = re.compile(r'text')
a.
```
`a.` does not suggest any thing

**Comment by jakebailey** [comment] 2019-06-19 17:41
Duplicate of #1015. Needs to be specialized as per #535 like other things in `typing`.

**Closed by jakebailey** 2019-06-19 17:41 UTC
