### ISSUE TITLE
Support type comments

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/python-language-server#259] opened 2018-10-15 18:44 UTC
Microsoft/vscode-python#2820

E.g.
```python
def foo():
    a = func()  # type: int
```
The `a` variable should be recognized as an `int`. See [PEP 484's type comments](https://www.python.org/dev/peps/pep-0484/#type-comments) section for details.

**Comment by jakebailey** [comment] 2018-10-15 18:45
Duplicate of #7.

**Closed** 2018-10-15 18:49 UTC
Labels: duplicate
